let lastEvent="",comboTracker=[],buildKeys=0,testKeyCount=0,armorCount="";
const dropHZ=document.getElementById("dropHZ"),dropWeapon=document.getElementById("dropWeapon"),weaponType=document?.getElementById("dropWeaponType"),dropMon=document.getElementById("dropMonster"),dropQuest=document.getElementById("dropQuest"),weaponTypes=[["LightBowGun"],["GreatSword"],["ChargeBlade"],["InsectGlaive"],["SwordNShield"],["DualBlades"],["SwitchAxe"],["LongSword"],["Lance"],["HeavyBowGun"],["Bow"],["HuntingHorn"],["Gunlance"],["Hammer"]],updateSelectedSkillsDisplay=()=>{var a=getCurrentSelectedSkills();
a=getCurrentArmorSkills(a);a=Object.entries(a).sort();const b=document.querySelector("#EquippedSkillDisplay output");let c="";a.forEach(([d,e])=>{c+=`${d}: ${+e}<br>`});b.innerHTML=c},getGrade=(a,b)=>a.includes("S")||b.includes("S")?"S":b<=a?b:a,info={};
async function getInfo(){try{const a=window.location.href.slice(0,window.location.href.lastIndexOf("/"));weaponTypeSelect();const b=fetch(`${window.location.href.slice(0,window.location.href.lastIndexOf("/"))}/json/monster.json`).then(g=>g.json()).then(g=>{info.monster=g}),c=fetch(`${a}/json/rampage.json`).then(g=>g.json()).then(g=>{info.rampage=g}),d=fetch(`${a}/json/types.json`).then(g=>g.json()).then(g=>{info.types=g}),e=fetch(`${a}/json/skills.json`).then(g=>g.json()).then(g=>{info.skills=g}),
h=fetch(`${a}/json/quest.json`).then(g=>g.json()).then(g=>{info.quest=g}),l=fetch(`${a}/json/LightBowGun.json`).then(g=>g.json()).then(g=>{info.LightBowGun=g}),k=fetch(`${a}/json/ammo.json`).then(g=>g.json()).then(g=>{info.ammo=g}),f=await Promise.all([l,d,c]).then(()=>{});await Promise.all([b,e,h,k,f]).then(()=>{classChange();document.querySelectorAll("#dropMonster>option").forEach((g,m)=>{"Toadversary"===g.textContent&&(document.getElementById("dropMonster").selectedIndex=m)})}).then(()=>info);
if(Object.values(document.getElementsByTagName("SCRIPT")).some(g=>g.src.includes("backup.js"))){const g=document.createElement("script");g.src="setCreation.js";document.body.append(g);const m=document.createElement("script");m.src="setBuilderWorker.js";document.body.append(m)}weaponTypes.push("armor");fetch(`${a}/json/charms.json`).then(g=>g.json()).then(g=>{const m=[],n=document.createDocumentFragment();for(let p=0,q=0;;){if(0===p){const r=document.createElement("option");r.value=Object.values(g)[q][0]?.grade;
r.textContent=`${Object.keys(g)[q]} +${Object.values(g)[q][1]}`;n.appendChild(r)}if(++q===Object.keys(g).length)if(q=0,++p===Object.keys(g).length)break;else 1===p&&(document.getElementById("charmSkill1")?.appendChild(n.cloneNode(!0)),document.getElementById("charmSkill2")?.appendChild(n.cloneNode(!0)));p!==q&&"Bludgeoner"!==Object.keys(g)[p]&&"Bludgeoner"!==Object.keys(g)[q]&&(null===info.types.Lvl4[Object.keys(g)[p]]||9<=info.types.qurious[Object.keys(g)[p]]||!info.types.qurious[Object.keys(g)[p]]||
2>info.types.Lvl4[Object.keys(g)[p]])&&(null===info.types.Lvl4[Object.keys(g)[q]]||9<=info.types.qurious[Object.keys(g)[q]]||!info.types.qurious[Object.keys(g)[q]]||3>info.types.Lvl4[Object.keys(g)[q]])&&!info.types.decoLevels[0].some(r=>Object.keys(r)[0]===Object.keys(g)[p])&&!info.types.decoLevels[0].some(r=>Object.keys(r)[0]===Object.keys(g)[q])&&3<=Object.values(g)[p][1]&&2<=Object.values(g)[q][2]&&m.push({skills:{[Object.keys(g)[p]]:Object.values(g)[p][1],[Object.keys(g)[q]]:Object.values(g)[q][2]},
grade:getGrade(Object.values(g)[p][0]?.grade,Object.values(g)[q][0]?.grade)})}info.charms=m});weaponTypes.slice(1).forEach(g=>{fetch(`${a}/json/${g}.json`).then(m=>m.json()).then(m=>{info[g]=m}).then(()=>{info.armor&&(armorSelect(),updateSelectedSkills(window.event))})})}catch(a){console.error(a)}}getInfo();const getArmorTypes=()=>["helm","chest","arm","waist","leg"],timesUsed=(a,b=comboTracker,c=0)=>{b.forEach(d=>{d==a&&++c});return c};
function dataCompile(a=window?.event){updateSelectedSkills();/BowGun/.test(weaponType.value)?rangedDPS(a):meleeDPS(a)}const resetTable=a=>{let b=0,c=2;const d=document.querySelectorAll("#dpsBody>tr>td:nth-child(n+3)");for(;7!==++c||(c=2,++b!==a.length);)d[0].textContent=a[b][c]};
function rangedDPS(a){document.querySelector("output.elementalAug").value=0;document.getElementById("elementalResult").value="+0";document.querySelector("output.sharpnessAug").value=0;document.getElementById("sharpnessResult").value="+0";const b=[],c=[];let d={};var e=!0;const h=getWeaponMR();["Shot","Sever","Blunt","IgnoreHZV"].forEach(f=>{h[f]=getInitialStats(h,f)});const l=getUsedAttacks();for(let f=0;f<Object.keys(l).length;f++){let g={...h[Object.values(l)[f].type],...Object.values(l)[f]};g=
getDependantSkills(g);g=getRemainingSkills(g);g=damageCalculations(g);/Demon|Armor|Wyvern Blast|Glide|Wyvernsn|Guard/.test(g.attackName)?d.ticsAdjust=1:d=calculateAmmoFrames(g);var k=~~((~~g.efr+~~g.efe)*d.ticsAdjust);const m=~~(~~g.rawCrit+~~g.eleCrit),n=~~(~~g.rawNon+~~g.eleNon),p=formatNumbers(~~(.99+document.getElementById("health").value/k));let q=/Stic|Slic/.test(g.attackName)?5+~~(.98+60/d.shotsPerMin)*~~(.99+document.getElementById("health").value/k):~~(.98+60/d.shotsPerMin)*~~(.99+document.getElementById("health").value/
k);q=formatNumbers(q);k=[g.attackName,[`${~~g.rawNon} / ${~~g.rawCrit}`],[`${~~g.eleNon} / ${~~g.eleCrit}`],[`${~~n} / ${~~m}`],k,"NaN%"===d.shotsPerGain||"0.00%"===d.shotsPerGain?"No Gain":d.shotsPerGain,/(\d{2},\d{3})/.test(p)?"N / A":p,/(\d{2},\d{3})/.test(q)?"N / A":q];b.push(k);k=[g.attackName,g.rawMV,void 0===d.reloadSpeed?" N / A ":d.reloadSpeed,void 0===d.recoilSpeed?" N / A ":d.recoilSpeed,isNaN(d.clipSize)?"N / A":d.clipSize,g.ticsPer+1,void 0===d.shotsPerMinBase?" N / A ":d.shotsPerMinBase,
void 0===d.shotsPerMin?" N / A ":d.shotsPerMin];c.push(k);e&&(e=[["Stat","Raw","Ele Pierce"],["Base",~~g.baseRaw,~~(22*(1+g.raw/100))],["True",~~g.raw,~~((22*g.BEM+g.BE)*(1+g.raw/100))],["eTrue",~~(g.raw*getCritBoost(g.aff,g.Crit).PRM*g.PRM*g.augPRM),~~((22*g.BEM+g.BE)*(1+g.raw/100)*g.PEM*g.augPEM*getCritEle(g.aff,g.Crit).PEM)],["EFR/EFE",~~(g.raw*getCritBoost(g.aff,g.Crit).EFR*g.PRM*g.augPRM),~~((22*g.BEM+g.BE)*(1+g.raw/100)*g.PEM*g.augPEM*getCritEle(g.aff,g.Crit).EFE)],["Critical"].concat(Number(getCritBoost(g.aff).EFR).toFixed(3),
Number(getCritEle(g.aff).EFE).toFixed(2)),["Affinity",~~(100*g.aff)]],createTable(e),e=!1)}b.splice(0,0,"Ammo Type;Raw;Element;Total;Effective;RPM Gain;Shots \n To Kill;Seconds \n To Kill".split(";"));buildDamageTable(b,"dps",a);c.splice(0,0,["Ammo Type","Raw MV","Reload","Recoil","Clip Size",["Procs Per","Maximum Tics Per Shot At Optimal FPS"],["RPM Base","Shots Per Minuite Including Recoil Down And Reload Speed"],["Current RPM","Shots Per Minuite With AmmoUp And Spare Shot"]]);buildDamageTable(c,
"ammo",a)}
function meleeDPS(a){const b=performance.now(),c=["Combo;Attack Name;MV;Raw;Element;Total;Effective".split(";")];let d=[0,0,0,0,0,0,0,0],e=-1,h={};document.getElementById("Sharpness");const l=getWeaponMR();["Shot","Sever","Blunt","IgnoreHZV"].forEach(k=>{l[k]=getInitialStats(l,k)});Object.values(getUsedAttacks()).forEach(k=>{++e;let f={...k,...l[k.type]};f=getDependantSkills(f);/input/.test(a?.target?.className)&&"Combo Damage"===f.attackName&&(updateComboTracker(),updateComboDisplay());"Combo Damage"===
f.attackName&&(h="Bow"===weaponType.value?hitsPerColorSharp()[1]:getComboHitsAndSetSharpness(f.aff));f=getRemainingSkills(f);f=damageCalculations(f);comboTracker.includes(e.toString())&&Object.entries(h).filter(m=>0<m[1].length).forEach(m=>{if(timesUsed(e,m[1])){var {PRM:n,PEM:p}=!1===f.noSharpMod?info.skills.Sharpness[capital(m[0])]:{PRM:1,PEM:1};m=timesUsed(e,m[1]);d=[d[0]+=Number(~~(f.rawMV*m)),d[1]+=Number(~~(f.rawNon*n)*m),d[2]+=Number(~~(f.rawCrit*n)*m),d[3]+=Number(~~(f.eleNon*p)*m),d[4]+=
Number(~~(f.eleCrit*p)*m),d[5]+=Number(~~(f.rawNon*n)*m+~~(f.eleNon*p)*m),d[6]+=Number(~~(f.rawCrit*n)*m+~~(f.eleCrit*p)*m),d[7]+=Number(~~(f.efr*n)*m+~~(f.efe*p)*m)]}});k=info.skills.Sharpness[document.getElementById("Sharpness").selectedOptions[0].textContent.trim()];if("Bow"===weaponType.value&&"Shot"!==f.type)switch(document.getElementById("BowCoating").selectedOptions[0].textContent){case "Power":k="1.35";break;case "Close Range":k="1.32";break;case "Close Range+":k="1.39"}var g=["replaceME",
f.attackName,f.rawMV,`${formatNumbers(~~(f.rawNon*k.PRM))} / ${formatNumbers(~~(f.rawCrit*k.PRM))}`,`${formatNumbers(~~(f.eleNon*k.PEM))} / ${formatNumbers(~~(f.eleCrit*k.PEM))}`,`${formatNumbers(~~(f.rawNon*k.PRM)+~~(f.eleNon*k.PEM))} / ${formatNumbers(~~(f.rawCrit*k.PRM)+~~(f.eleCrit*k.PEM))}`,formatNumbers((~~(f.efe*k.PEM)+~~(f.efr*k.PRM))*(f.ticsPer+1))];c.push(g);g="none"===lower(f.eleType)?0:f.ele;k=[[["Stat"],["Raw"],[f.eleType]],["Base",~~f.baseRaw,f.baseEle],["True",~~f.raw,~~g],["eTrue",
~~(f.raw*getCritBoost(f.aff,f.Crit).PRM*f.PRM*f.augPRM*k.PRM),~~(g*getCritEle(f.aff,f.Crit).PEM*f.PEM*f.augPEM*k.PEM)],["EFR/EFE",~~(f.raw*getCritBoost(f.aff,f.Crit).EFR*f.PRM*f.augEFR*k.PRM),~~(g*getCritEle(f.aff,f.Crit).EFE*f.PEM*f.augPEM*f.augEFR*k.PEM)],["Critical"].concat(Number(getCritBoost(f.aff).EFR).toFixed(3),Number(getCritEle(f.aff).EFE).toFixed(2)),["Sharp."].concat(Object.values(Object.values(info.skills.Sharpness)[7-document.getElementById("Sharpness").selectedIndex])),["Affinity",~~(100*
f.aff)]];createTable(k)});"Gunlance"===weaponType.value?(gunlanceShelling(c,d,a),console.log((performance.now()-b)/1E3),gunlanceShelling(532)):(c.splice(1,1,["replaceME","Combo Damage",`${formatNumbers(d[0])}`,`${formatNumbers(d[1])} / ${formatNumbers(d[2])}`,`${formatNumbers(d[3])} / ${formatNumbers(d[4])}`,`${formatNumbers(d[5])} / ${formatNumbers(d[6])}`,`${formatNumbers(d[7])}`]),buildDamageTable(c,"dps",a),console.log((performance.now()-b)/1E3))}
function getRampageSkills(a={...info[weaponType.value].weapons[dropWeapon.value]}){for(let c=0;6>c;c++){var b=document.querySelectorAll("#weaponRampage>select")[c];if("none"===b.style.display)break;b=info.rampage["Rampage-Up Skill"][b.value];if(void 0!==b)for(const d of Object.keys(b))a[d]+=b[d]}/BowGun/.test(weaponType.value)||(a.eleType=/Fire|Water|Thunder|Ice|Dragon|Blase|Sleep|Poison|Para/.test(document.getElementById("weaponRampage").children[1].value)?document.getElementById("weaponRampage").children[1].value.match(/Fire|Water|Thunder|Ice|Dragon|Blase|Sleep|Poison|Para/)[0]:
a.eleType);return{...a}}
const getWeaponMR=()=>{const a={...info[weaponType.value].weapons[dropWeapon.value]};/Bow/.test(weaponType.value)?"HeavyBowGun"===weaponType.value?(10===a.rank&&(a.baseRaw+=15),"Power"===document.getElementById("BowgunBarrel")?.selectedOptions[0]?.textContent&&(a.baseRaw=~~(a.baseRaw*(2>document.getElementById("Tune-Up").selectedIndex?1.125:1.15)))):"LightBowGun"===weaponType.value?(10===a.rank&&(a.baseRaw+=7),"Long"===document.getElementById("BowgunBarrel")?.selectedOptions[0]?.textContent&&(a.baseRaw=
~~(a.baseRaw*(2>document.getElementById("Tune-Up").selectedIndex?1.05:1.075)))):"Bow"===weaponType.value&&10===a.rank&&(a.baseRaw+=10):10!==a.rank||/Water|Ice|Thunder|Fire|Dragon/.test(a.eleType)?10===a.rank&&(a.baseRaw+=15,a.baseEle="GreatSword"===weaponType.value?a.baseEle+30:"lance"===weaponType?.value||"Gunlance"===weaponType?.value?a.baseEle+21:a.baseEle+18):a.baseRaw+=30;a.baseRaw+=+document.querySelector("output.attackAug + output").value.slice(-2);var b=+document.querySelector("output.affinityAug + output").value.slice(-2);
a.elementalAug+=+document.querySelector("output.elementalAug + output").value.slice(-2);a.aff=a.aff?a.aff+b:b;"None"!==a.eleType?(b="GreatSword"===weaponType.value?[0,5,10,15,20,25,33,43][info.augIndex.elementalAug]:"lance"===weaponType?.value||"Gunlance"===weaponType?.value?[0,3,6,10,14,18,24,32][info.augIndex.elementalAug]:[0,3,6,9,12,15,20,27][info.augIndex.elementalAug],a.baseEle+=b,document.getElementById("elementalResult").value=`+ ${b}`):document.querySelector("output.elementalAug").value=
0;a.baseAff=a.aff;return JSON.parse(JSON.stringify(a))},getRangedSkills=a=>{/Pierc/.test(a.attackName)?a.getSkills.push(info.skills.PierceUp[document.getElementById("PierceUp").selectedIndex]):/Spread/.test(a.attackName)?a.getSkills.push(info.skills.SpreadUp[document.getElementById("SpreadUp").selectedIndex]):/Normal|Rapid/.test(a.attackName)&&a.getSkills.push(info.skills.NormalRapidUp[document.getElementById("NormalRapidUp").selectedIndex]);/RF+/.test(a.attackName)&&a.getSkills.push(info.skills.RapidFireUp[document.getElementById("RapidFireUp").selectedIndex]);
/Wyvern|Dragon Piercer/.test(a.attackName)&&a.getSkills.push(info.skills.SpecialAmmoBoost[document.getElementById("SpecialAmmoBoost").selectedIndex]);/BowGun/.test(weaponType.value)&&("HeavyBowGun"===weaponType.value&&(/Sticky|Wyvern/.test(a.attackName)&&(a.augEFR*=info.skills.Bombardier[document.getElementById("Bombardier").selectedIndex][a.attackName.match("Sticky|Wyvern")[0]][1],a.augPRM*=info.skills.Bombardier[document.getElementById("Bombardier").selectedIndex][a.attackName.match("Sticky|Wyvern")[0]][0]),
/snipe|heart|Cluster/.test(a.attackName)||(a.PRM*=info.skills.ChargeLevel[document.getElementById("ChargeLevel").selectedIndex].PRM,a.NoEleBuff?a.baseEle*=info.skills.ChargeLevel[document.getElementById("ChargeLevel").selectedIndex].PEM:a.PEM*=info.skills.ChargeLevel[document.getElementById("ChargeLevel").selectedIndex].PEM)),"LightBowGun"===weaponType.value&&/Pierce|Spread|Normal/.test(a.attackName)&&0<document.getElementById("CriticalFirePower").selectedIndex&&(/Normal/.test(a.attackName)?a.PRM*=
1.3:/Spread/.test(a.attackName)?a.PRM*=1.2:/Pierce/.test(a.attackName)&&(a.PRM*=1.1)));"Bow"!==weaponType.value||/Stake/.test(a.attackName)||a.getSkills.push(info.skills.BowCoating[document.getElementById("BowCoating").selectedIndex]);return getStats(a)},getMeleeSkills=a=>{"LongSword"!==weaponType.value||/Helm Breaker|Serene/.test(a.attackName)?/Helm Breaker|Serene/.test(a.attackName)&&a.getSkills.push(/Helm Breaker/.test(a.attackName)?a.getSkills.push(info.skills.Helmbreaker[document.getElementById("Helmbreaker").selectedIndex]):
a.getSkills.push(info.skills.SerenePose[document.getElementById("SerenePose").selectedIndex])):a.getSkills.push(info.skills.SpiritGauge[document.getElementById("SpiritGauge").selectedIndex]);if("GreatSword"===weaponType.value){const b=a.attackName.match(/Charged Slash|Rising Slash|Wide Slash|Strong Charged Slash|True Charged Slash|Rage Slash/);b&&0<document.getElementById("StrongarmStance").selectedIndex&&(a.PRM*=info.skills.StrongarmStance[b][0],a.PEM*=info.skills.StrongarmStance[b][1]);/(?<!Tackle )Lv[1-3]/.test(a.attackName)&&
(a.rawMV*=Number(`1.${a.attackName.match(/(?<=Lv)[1-3]/)[0]}`),a.rawMV=a.rawMV.toFixed(1))}"ChargeBlade"===weaponType.value&&(/3rd|(?<!Midair |Axe: )UED|(?<!Charged )Sword(?!.*Shield)/.test(a.attackName)||a.getSkills.push(info.skills.savageAxe[document.getElementById("savageAxe").selectedIndex]),"Impact Phial"===a.phialType?a.getSkills.push(info.skills.impShieldCharge[document.getElementById("impShieldCharge").selectedIndex]):a.getSkills.push(info.skills.eleShieldCharge[document.getElementById("eleShieldCharge").selectedIndex]));
return getStats(a)};function getDependantSkills(a){a.getSkills=[];"FireWaterIceThunderDragon".includes(a.eleType)&&document.querySelectorAll(`.${lower(a.eleType)}`).forEach(b=>{0<b.selectedIndex&&a.getSkills.push(info.skills[b.id][b.selectedIndex])});return weaponType.value.includes("Bow")?getRangedSkills(a):getMeleeSkills(a)}function getEnrage(){return"Enraged"===document.getElementById("dropEnraged").value?info.monster[dropMon.value]?.anger_data:1}
const getWeaknessExploit=a=>45<=a?info.skills.WeaknessExploit[Math.min(0,document.getElementById("WeaknessExploit").selectedIndex)].aff:0;
function getInitialStats(a,b){null===comboTracker[0]&&(comboTracker=[]);a.baseRaw+=!0===a.Draw?Number(document.getElementById("PunishingDraw").value):0;a.BR=0;a.BRM=1;a.PRM=1;a.BEM=1;a.BE=0;a.PEM=1;const c={};let d=[];a.getSkills=[];Object.values(info.types[b]).forEach(e=>{document.getElementById([e])?.style.display.includes("none")||!document.getElementById([e]).selectedIndex||c[e]||a.getSkills.push(info.skills[e][document.getElementById([e]).selectedIndex]);c[e]=1});a.PRM*=document.getElementById("DemonAmmo").checked&&
/(Sever|Blunt)/.test(a.type)?1.1:1;document.querySelectorAll("input.skillButton").forEach(e=>{e.checked&&info.skills[e.id]&&!c[e.id]?(a.getSkills.push(info.skills[e.id]),c[e.id]=1):info.skills[e.id]||console.log(e.id)});document.getElementById("enrageDisplay").textContent=`${~~(100*getEnrage())}%`;"Enraged"===document.getElementById("dropEnraged").value&&(d.push("Agitator"),a.PEM*=getEnrage(),a.PRM*=getEnrage());"DualBlades"===weaponType.value&&(a.BEM*=info.skills.ArchdemonMode[document.getElementById("ArchdemonMode").selectedIndex].BEM,
a.BEM*=/\[Feral Demon Mode\]/.test(a.attackName)?1:info.skills.DemonMode[document.getElementById("DemonMode").selectedIndex].BEM,a.BRM*=/\[Demon Mode\]/.test(a.attackName)?1:info.skills.FeralDemonMode[document.getElementById("FeralDemonMode").selectedIndex].BRM,a.aff+="Hellion Mode"===document.getElementById("weaponRampage0").value?20:0);"Bow"===weaponType.value&&(d=d.concat("UpperCrit","HerculesDraw"));d.forEach(e=>{!c[e]&&document.getElementById([e]).selectedIndex&&(c[e]=1,a.getSkills.push(info.skills[e][document.getElementById([e]).selectedIndex]))});
getStats(a);"Kushala Daora Soul"===document.getElementById("weaponRampage0").value&&(a.aff+=15);a.aff+=getWeaknessExploit(getRawHZ(b));a.aff=Math.min(a.aff,100)/100;return{...a}}
function updateComboTracker(){if(document.getElementsByClassName("inputs")?.length&&!Number.isNaN(Number(window?.event?.target.id))&&"0"!==window?.event?.target.id){let a=document.querySelectorAll(".inputs")[window?.event?.target.id].value-timesUsed(window?.event?.target.id);for(;0<a;)comboTracker.push(window.event.target.id),--a;for(;0>a;)comboTracker.splice(comboTracker.lastIndexOf(window?.event?.target.id),1),++a}}
function updateComboDisplay(){document.querySelectorAll("li.comboHits").forEach(b=>b.remove());let a;comboTracker.forEach(b=>{a=document.createElement("li");a.className=`${b} comboHits`;a.setAttribute("draggable","true");a.textContent=document.querySelector(`td#b${[b]}>output`).textContent;document.getElementById("comboCountDisplay").append(a)})}
const getInitialSharpness=()=>{let a=10*document.getElementById("Handicraft").selectedIndex;const {sharpness:b,handicraft:c,rank:d}=getWeaponMR();var e=10*(info.augIndex.sharpnessAug+(10===d?1:0));b.orange-=Math.max(0,e-b.red);b.red-=e;let h=-1===Object.values(document.getElementById("Sharpness")).indexOf(0)?6:Object.values(document.getElementById("Sharpness")).indexOf(0)-1;for(0!==b[Object.keys(b)[h]]?b[Object.keys(b)[h]]+=e:b[Object.keys(b)[h-1]]+=e;a;)e=Math.min(a,c.shift()),b[Object.keys(b)[h]]+=
e,++h,a-=e;return b};function applySharpnessSkills(a,b={...getInitialSharpness()}){var c=[];c=info.skills.RazorSharp[document.getElementById("RazorSharp").selectedIndex].Sharp;const d=info.skills.MastersTouch[document.getElementById("MastersTouch").selectedIndex].Sharp*a,e=0<a&&0<document.getElementById("MastersTouch").selectedIndex?sharpnessReduction(d)*sharpnessReduction(c):sharpnessReduction(c);return c=Object.entries(b).map(h=>~~(Number(h[1])*Number(e)))}
function listOfAllComboHits(){let [...a]=comboTracker;if(void 0!==comboTracker[0]&&null!==comboTracker[0]){let b=document.getElementsByClassName("inputComboRepeat")[0].value;for(;1<b;)a=a.concat(comboTracker),--b;return a}}
function getComboHitsAndSetSharpness(a=0){const [b,c,d]=hitsPerColorSharp(a);document.getElementById("Sharpness").selectedIndex=6-b.lastIndexOf(0);b.forEach((e,h)=>{document.querySelector("#sharpnessContainer").children[6-h].style.width=`${e/d*90}%`;document.querySelector("#sharpnessContainer").children[6-h].textContent=.1>e?"":~~e});return c}
function hitsPerColorSharp(a=0,b=listOfAllComboHits()){const c={purple:[],white:[],blue:[],green:[],yellow:[],orange:[],red:[]};a="Bow"!==weaponType.value?applySharpnessSkills(a).reverse():[0,0,0,1,0,0,0,0];const d=Object.values(a).reduce((h,l)=>h+l);if(b){const h=Object.keys(getUsedAttacks());let l=0;const k=Object.keys(c),f=getAttacks();a:for(let g of b){var e=h[g];b=f[e].ticsPer+1;e=getHitsPerTic(f[e].hitsOfSharp,g);if("Gunlance"!==weaponType.value||27>g)for(;b--;){if(.1>a[l]&&7===++l)break a;
c[k[l]].push(g);a[l]-=e}}}return[a,c,d]}function getHitsPerTic(a,b){return document.getElementById("ProtectivePolish").checked||"Bow"===weaponType.value?0:"Gunlance"!==weaponType.value||27<b?"DualBlades"!==weaponType.value?a:a/3:1}
function getRemainingSkills(a,b=getWeaponMR()){[a.augEFR,a.augPRM,a.augPEM]=[1,1,1];a.augPEM*="Valstrax Soul"===document.getElementById("weaponRampage0").value&&"Dragon"===a.eleType?1.2:1;[a.augEFR,a.augPRM]="Dulling Strike"===document.getElementById("weaponRampage0").value&&5>document.getElementById("Sharpness").selectedIndex?[1.02,1.2]:[a.augEFR,a.augPRM];var c=Object.values(info.monster[dropMon.value]?.species);c&&("Invalid"!==c[1]&&"Wyvern Exploit"===document.querySelector("#weaponRampage0").value||
document.querySelector("#weaponRampage0").value.includes(c[2])||"Invalid"!==c[3]&&"Fanged Exploit"===document.querySelector("#weaponRampage0").value)&&(a.PRM*=1.05);/blight Exploit/.test(document.getElementById("weaponRampage0").value)&&(a.PRM*=1.1);"Magnamalo Soul"===document.getElementById("weaponRampage0").value&&(a.BR+=12);if("IgnoreHZV"===a.type&&"LightBowGun"===weaponType.value||"ChargeBlade"===weaponType.value)a.augEFR*=info.skills.Bombardier[document.getElementById("Bombardier").selectedIndex][1],
a.augPRM*=info.skills.Bombardier[document.getElementById("Bombardier").selectedIndex][0],"SwitchAxe"===weaponType.value&&/Sword|ZSD|ED/.test(a.attackName)&&"Impact Phial"===a.phialType&&(a.BRM*=1.15),"SwitchAxe"===weaponType.value&&/Sword|Elemental|ED/.test(a.attackName)&&"Elemental Phial"===a.phialType&&(a.BEM*=1.45);"None"!==a.eleType&&(a.PEM*=0===b.rampageSlots&&"Elemental Exploit"===document.getElementById("weaponRampage0").value&&25<=getEleHZ(a.eleType)?1.3:1,a.PEM*=0!==b.rampageSlots&&"Element Exploit"===
document.getElementById("weaponRampage0").value&&25<=getEleHZ(a.eleType)&&"none"!==lower(a.eleType)?1.15:1,a.PEM*=20<=getEleHZ(a.eleType)&&"none"!==lower(a.eleType)?info.skills.ElementExploit[document.getElementById("ElementExploit").selectedIndex].PEM:1);if("ChargeBlade"===weaponType.value||"SwitchAxe"===weaponType.value)a.BRM*=/Morph Slash|Condensed Spinning|Up Roundslash/.test(a.attackName)?info.skills.RapidMorph[document.getElementById("RapidMorph").selectedIndex].BRM:1;0<document.getElementById("Sharpness").selectedIndex&&
0<document.getElementById("Bludgeoner").selectedIndex&&(a.BRM*=1===document.getElementById("Bludgeoner").selectedIndex&&4>document.getElementById("Sharpness").selectedIndex?1.05:1,a.BRM*=2===document.getElementById("Bludgeoner").selectedIndex&&4>document.getElementById("Sharpness").selectedIndex?1.1:1,a.BRM*=3===document.getElementById("Bludgeoner").selectedIndex&&5>document.getElementById("Sharpness").selectedIndex?1.1:1);!/Wyvern/.test(a.attackName)&&Object.keys(info.skills.ChargeMaster).includes(weaponType.value)&&
!0===a.ChargeMaster?a.BEM*=info.skills.ChargeMaster[weaponType.value][document.getElementById("ChargeMaster").selectedIndex].BEM:!0===a.ChargeMaster&&!0===a.NoEleBuff&&(a.baseEle*=/Wyvern/.test(a.attackName)?info.skills.ChargeMaster["HeavyBowGun Wyvern"][document.getElementById("ChargeMaster").selectedIndex].BEM:info.skills.ChargeMaster[weaponType.value][document.getElementById("ChargeMaster").selectedIndex].BEM);c={};[c.PRM,c.PEM]=!1===a.noSharpMod&&/sever|blunt/.test(lower(a.type))?[JSON.parse(document.getElementById("Sharpness").value).PRM,
JSON.parse(document.getElementById("Sharpness").value).PEM]:[1,1];a.PRM*=~~(25/c.PRM)>=getRawHZ(a.type)?info.skills.MindsEye[document.getElementById("MindsEye").selectedIndex].PRM:1;0===b.rampageSlots&&"Brutal Strike"===document.getElementById("weaponRampage0").value&&0>a.aff?(a.efrMulti=1+-.2*a.aff*1.5- -.8*a.aff*.75,a.critBoost=1.5):0!==b.rampageSlots&&"Brutal Strike"===document.getElementById("weaponRampage0").value&&0>a.aff&&(a.efrMulti=1+-.5*a.aff- -.5625*a.aff,a.critBoost=1.5);"Shot"===a.type&&
(a.augPRM*=info.skills.Marksman[document.getElementById("Marksman").selectedIndex][0],a.augEFR*=info.skills.Marksman[document.getElementById("Marksman").selectedIndex][1]);a.NoSneak||(a.augPRM*=info.skills.SneakAttack[document.getElementById("SneakAttack").selectedIndex].PRM,a.augEFR*=info.skills.SneakAttack[document.getElementById("SneakAttack").selectedIndex].PRM);return{...a}}
function getCritEle(a,b=!0){return b?{PEM:info.skills.CriticalElement[document.getElementById("CriticalElement").selectedIndex].PEM,EFE:1+(info.skills.CriticalElement[document.getElementById("CriticalElement").selectedIndex].PEM-1)*a}:{PEM:1,EFE:1}}function getCritBoost(a,b=!0){return b?{PRM:info.skills.CriticalBoost[document.getElementById("CriticalBoost").selectedIndex].PRM,EFR:1+(info.skills.CriticalBoost[document.getElementById("CriticalBoost").selectedIndex].PRM-1)*a}:{PRM:1,EFR:1}}
function damageCalculations(a){if(!1===a.Raw)[a.raw,a.rawNon,a.efr,a.rawCrit]=[0,0,0,0];else{a.raw=Math.min(~~(~~(~~a.baseRaw*a.BRM+a.BR+.1)*(document.getElementById("HuntingHornAttack").checked?1.1:1)),2600);var b=a.raw*a.PRM*getRawHZ(lower(a.type))*a.rawMV/1E4;a.rawNon=~~(.5+Math.max(1,b*a.augPRM));a.efr=~~(.5+Math.max(1,b*a.augEFR*getCritBoost(a.aff,a.Crit).EFR));a.rawCrit=~~(.5+Math.max(1,b*a.augPRM*getCritBoost(a.aff,a.Crit).PRM))}Object.prototype.hasOwnProperty.call(a,"NoEleBuff")&&!0===a.NoEleBuff?
[a.ele,a.eleNon,a.efe,a.eleCrit]=[a.baseEle,a.baseEle,a.baseEle,a.baseEle]:(a.eleAmmo=/BowGun/.test(weaponType.value)&&"None"!==a.eleType?1+a.raw/100:1,a.ele=~~(Math.min(a.baseEle*a.BEM+a.BE,365)*a.eleAmmo+.1),b=a.ele*a.PEM*(getEleHZ(a.eleType)/100)*a.eleMV*a.augPEM,a.eleNon=~~(.5+Math.max(1,b)),a.efe=~~(.5+Math.max(1,b*getCritEle(a.aff,a.Crit).EFE)),a.eleCrit=~~(.5+Math.max(1,b*getCritEle(a.aff,a.Crit).PEM)));return{...a}}const sharpnessReduction=a=>1/(1-a);
function gunlanceShelling(a,b,c,d){const e=new RegExp(`${getWeaponMR().shellingType} Lv${getWeaponMR().shellingLevel}`);let h=1,l=1;Object.entries(getAttacks()).forEach((k,f)=>{e.test(k[0])&&(h=~~(k[1].rawMV*info.skills.Bombardier[document.getElementById("Bombardier").selectedIndex][0]*info.skills.Artillery[document.getElementById("Artillery").selectedIndex].BRM),l=~~(k[1].rawMV*info.skills.Bombardier[document.getElementById("Bombardier").selectedIndex][1]*info.skills.Artillery[document.getElementById("Artillery").selectedIndex].BRM),
a.push(["replaceME",k[0],0,`${h} / ${h}`,`${k[1].baseEle} / ${k[1].baseEle}`,`${(h+k[1].baseEle)*(k[1].ticsPer+1)} / ${(h+k[1].baseEle)*(k[1].ticsPer+1)}`,l,k[1].baseEle,(l+k[1].baseEle)*(k[1].ticsPer+1)]),b[0]+=0,b[1]+=h*timesUsed(f+27),b[2]+=h*timesUsed(f+27),b[3]+=k[1].baseEle*timesUsed(f+27),b[4]+=k[1].baseEle*timesUsed(f+27),b[5]+=(h+k[1].baseEle)*(c.ticsPer+1)*timesUsed(f+27),b[6]+=(h+k[1].baseEle)*(c.ticsPer+1)*timesUsed(f+27),b[7]+=(l+k[1].baseEle)*(c.ticsPer+1)*timesUsed(f+27))});/Inputs|inputButton/.test(window?.event?.target.className)||
buildDamageTable(a,"dps",d);document.getElementById("c0").innerHTML=`${formatNumbers(b[0])}`;document.getElementById("d0").innerHTML=`${formatNumbers(b[1])} / ${formatNumbers(b[2])}`;document.getElementById("e0").innerHTML=`${formatNumbers(b[3])} / ${formatNumbers(b[4])}`;document.getElementById("f0").innerHTML=`${formatNumbers(b[5])} / ${formatNumbers(b[6])}`;document.getElementById("g0").innerHTML=`${formatNumbers(b[7])}`}
function createTable(a){let b=document.createElement("table"),c="";for(let d=0;d<a.length;d++){c+="<tr>";for(let e=0;e<a[d].length;e++)c=1==d?c+("<td title='Base Stats + Augments'>"+a[d][e]+"</td>"):2==d?c+("<td title='Value Seen In Game'>"+a[d][e]+"</td>"):3==d?c+("<td title='Total Damage Output If Critical'>"+a[d][e]+"</td>"):4==d?c+("<td title='Averaged Damage Output'>"+a[d][e]+"</td>"):5==d?c+("<td title='Critical Damage Increase'>"+a[d][e]+"</td>"):6!=d||weaponType.value.includes("Bow")?7==d||
6==d&&weaponType.value.includes("Bow")?c+("<td title='Total Affinity'>"+a[d][e]+"</td>"):c+("<td>"+a[d][e]+"</td>"):c+("<td title='Sharpness Modifier'>"+a[d][e]+"</td>");c+="</tr>"}b.innerHTML=c;document.querySelector("#statsTableDiv").replaceChildren(b)}
function buildDamageTable(a,b){const c=!document.getElementById("ammoTable").classList.contains("augInvis")&&weaponType.value.includes("BowGun"),d=document.getElementById("dpsTable").classList.contains("augInvis")||!weaponType.value.includes("BowGun"),e=/gray/.test(document.getElementById("filterCombo").className)?document.querySelectorAll(".a"):document.querySelectorAll(".a:not(.gray)");let h=0;const l=document.querySelector(`#${b}Head`),k=document.querySelector(`#${b}Body`),f=document.createElement("table"),
g=document.createElement("thead");/BowGun/.test(weaponType.value)&&"stats"!==b?g.className="tableRowRanged":"stats"!==b&&(g.className="tableRowMelee");g.id=`${b}Head`;const m=document.createElement("tr"),n=document.createElement("tbody");n.id=`${b}Body`;a.splice(0,1)[0].forEach(p=>{const q=document.createElement("th");Array.isArray(p)&&(document.createTextNode(p[0]),q.title=p[1]);p=document.createTextNode(p);q.appendChild(p);m.appendChild(q)});g.appendChild(m);l.replaceWith(g);a.forEach(p=>{const q=
document.createElement("tr");/BowGun/.test(weaponType.value)&&"stats"!==b?q.className="tableRowRanged":"stats"!==b&&(q.className="tableRowMelee");Object.values(p).forEach(r=>{if("replaceME"===r)if(document.getElementById("previousWeaponType").value===weaponType.value&&0<e.length&&(window?.event?.target===dropWeapon&&"ChargeBlade"!==weaponType.value||window?.event?.target!==dropWeapon)&&"BowChargePlus"!==window?.event?.target.id&&("Bow"===weaponType.value&&document.getElementById("previousWeapon").value===
dropWeapon.value||"Bow"!==weaponType.value))q.appendChild(e[h]),++h;else{var t=document.createElement("td");r=document.createElement("input");r.type="Number";r.className=`Combo skill ${h}`;r.Max=20;"Bow"===weaponType.value&&document.getElementById("previousWeapon").value!==dropWeapon.value&&(comboTracker=[],updateComboDisplay());0===h?(r.id="inputComboRepeat",r.Min=1,r.value=1,r.className="inputComboRepeat hitsOfSharpInputs inputs"):(r.id=h,r.className="inputs hitsOfSharpInputs",r.Min=0,r.value=0);
++h;t.appendChild(r);q.appendChild(t)}else t=document.createElement("td"),r=document.createTextNode(r),t.appendChild(r),q.appendChild(t)});n.appendChild(q);k.replaceWith(n)});f.setAttribute("id",`${b}Table`);n.className=/(BowGun)/.test(weaponType.value)?"rangedTable":"meleeTable";document.getElementById("damageContainer").className=/(BowGun)/.test(weaponType.value)?"rangedContainer":"meleeContainer";document.getElementById("ammoTable").classList.toggle("augInvis",c);document.getElementById("dpsTable").classList.toggle("augInvis",
!d);/BowGun/.test(weaponType.value)||document.getElementById("ammoTable").classList.add("augInvis");if("stats"!==b&&"ammo"!==b){const [p,...q]=/BowGun/.test(weaponType.value)?[h,"a","b","c","d","e","f","g","h"]:[h,"a","b","c","d","e","f","g"];/BowGun/.test(weaponType.value)&&!/BowGun/.test(document.getElementById("previousWeaponType").value)?document.querySelectorAll("#comboCountContainer").forEach(r=>r.style.display="none"):!/BowGun/.test(weaponType.value)&&/BowGun/.test(document.getElementById("previousWeaponType").value)&&
document.querySelectorAll("#comboCountContainer").forEach(r=>r.style.display="");document.getElementById("previousWeapon").value=dropWeapon.value;document.getElementById("previousWeaponType").value=weaponType.value;for(let r=0;r<p;++r)q.forEach((t,u)=>{document.getElementById(`${b}Body`).children[r].children[u].id=t+r;document.getElementById(`${b}Body`).children[r].children[u].className=`${t} ${r}`});weaponType.value.includes("BowGun")||document.querySelectorAll(`tbody#${b}Body>tr>td:nth-child(2)`).forEach((r,
t)=>{const u=document.createElement("td");u.innerHTML=`<button type="button" aria-pressed="false" id="${t}" class="inputButton dec"
                    >&#8681</button><button type="button" aria-pressed="false" id="${t}" class="inputButton inc">&#8679</button><output class="label">${r.textContent}</output>`;u.id=`b${t}`;u.className=`b ${t} inputContainer`;r.replaceWith(u)})}/blue/.test(document.getElementById("filterCombo").className)&&document.querySelectorAll(".a").forEach((p,q)=>{"none"===document.querySelectorAll(`.${q}`)[0].style.display&&document.querySelectorAll(`.${q}`).forEach(r=>r.style.display="none")})}
const setSpawn=()=>{document.querySelectorAll("#spawnArea>output").forEach(a=>a.remove());info.quest[dropQuest.value].target.forEach(a=>{a.name===dropMon.value&&a.spawn.forEach(b=>{const c=document.createElement("output");c.textContent=`Spawn Area ${b.block} ${b.lot}%`;document.getElementById("spawnArea").append(c)})})};
function monChart(){setSpawn();if(""!==dropQuest.value){const a=/Bow/.test(weaponType.value)?"shot":"H"===weaponType.value[0]?"blunt":"sever",b="Hit Zone;Sever;Blunt;Shot;Fire;Water;Thunder;Ice;Dragon".split(";"),c=document.createElement("table"),d=document.querySelector("#monTable");let e=info.monster[dropMon.value].parts.sort((l,k)=>k[a]===l[a]&&getWeaponMR().eleType?k[getWeaponMR().eleType]-l[getWeaponMR().eleType]:k[a]-l[a]);const h=document.createElement("tr");b.forEach(l=>{const k=document.createElement("th");
l=document.createTextNode(l);k.appendChild(l);h.appendChild(k)});c.appendChild(h);e.forEach(l=>{const k=document.createElement("tr");for(let g=0;9>g;++g){var f=0===g?`${l.part} ${l.state}`:l[lower(b[g])];const m=document.createElement("td");0!==g&&(f=document.getElementById("WaterBlight").checked&&4>g?Math.min(100,~~(Math.max(f,.63*f+22.2)+3)):+f,14>+f?m.setAttribute("class","F"):15>+f?m.setAttribute("class","C"):45>+f?m.setAttribute("class","B"):65>+f?m.setAttribute("class","A"):65<=+f&&m.setAttribute("class",
"S"),f=~~f);f=document.createTextNode(f);m.appendChild(f);k.appendChild(m)}c.appendChild(k)});c.setAttribute("id","monTable");d.replaceWith(c)}}document.querySelectorAll("select.demon").forEach(a=>{a.addEventListener("change",b=>{0<b?.target.selectedIndex&&(document.querySelectorAll(`.demon:not(#${b?.target.id})`)[0].selectedIndex=0,document.querySelectorAll(`.demon:not(#${b?.target.id})`)[1].selectedIndex=0)})});
document.querySelectorAll(`#${dropWeapon.id}, #${weaponType.id}`).forEach(a=>{a.addEventListener("change",b=>{b.target!==weaponType&&"ChargeBlade"!==weaponType.value||classChange()})});
document.querySelectorAll(`#${dropWeapon.id}, #${weaponType.id}`).forEach(a=>{a.addEventListener("change",()=>{if("Bow"===weaponType.value){document.querySelectorAll("#BowCoating>option").forEach(c=>c.remove());const b=[];getWeaponMR().coatings.forEach(c=>{const d=document.createElement("option");d.textContent=c;document.getElementById("BowCoating").append(d);b.push(info.skills[c])});info.skills.BowCoating=b}})});
function classChange(){if(info){weaponType.value.includes("Bow")&&(document.getElementById("Sharpness").selectedIndex=0);0<document.getElementsByClassName("inputs").length&&comboReset();switch(weaponType.value){case "DualBlades":info.skills.Burst=info.skills.BurstDualBlades;break;case "Bow":info.skills.Burst=info.skills.BurstBow;break;case "LightBowGun":info.skills.Burst=info.skills.BurstBowGun;break;case "HeavyBowGun":info.skills.Burst=info.skills.BurstBowGun;break;default:info.skills.Burst=info.skills.BurstStandard}info.skills.Bombardier=
/Gun|Charge/.test(weaponType.value)?info.skills.BombardierSource[weaponType.value]:[];document.querySelectorAll(`.skill:not(.${weaponType.value})`).forEach(a=>a.selectedIndex=0);document.querySelectorAll(".classSpecific").forEach(a=>{a.style.display="";a.parentElement.style.display="";a.classList.contains(weaponType.value)?"BUTTON"===a.tagName||"DIV"===a.tagName?a.style.display="":a.parentElement.style.display="":"BUTTON"===a.tagName||"DIV"===a.tagName?a.style.display="none":a.parentElement.style.display=
"none"});document.querySelectorAll("div").forEach(a=>{Object.values(a.children).some(b=>3>=a.childElementCount&&"SELECT"===b.tagName&&"none"!==a.style.display)&&a.classList.add("dropContainer")});document.getElementById("weaponId").textContent=weaponType.value;"ChargeBlade"===weaponType.value&&meleeElements()}}
function meleeElements(){"Impact Phial"===getWeaponMR().phialType?(document.getElementById("impShieldCharge").parentNode.style='display:"',document.getElementById("eleShieldCharge").parentNode.style="display:none",document.getElementById("eleShieldCharge").selectedIndex=0):"Element Phial"===getWeaponMR().phialType&&(document.getElementById("impShieldCharge").parentNode.style="display:none",document.getElementById("impShieldCharge").selectedIndex=0,document.getElementById("eleShieldCharge").parentNode.style=
'display:""')}document.addEventListener("keypress",a=>{a.key===["t","e","s","t"][Math.min(3,testKeyCount)]&&3>++testKeyCount||("Enter"===a.key&&3<=testKeyCount?(build("f"===armorCount?!1:!0),armorCount="",testKeyCount=0):/t|f/.test(a.key)&&3<=testKeyCount?armorCount=a.key:3>testKeyCount&&(testKeyCount=0))});function resetSkills(){document.querySelectorAll("div#setSearcher>div#skillSelect>div").forEach(a=>a.remove())}
document.getElementById("BowChargePlus").addEventListener("change",()=>{comboReset();updateComboDisplay()});
document.querySelectorAll(".scroll").forEach(a=>{"IMG"!==a.tagName&&"BUTTON"!==a.tagName||a.addEventListener("mousedown",()=>{Object.values(document.querySelectorAll("img.scroll")).forEach(b=>{b.classList.toggle("vis");b.classList.toggle("invis")});document.querySelector("img#redScroll")?.classList.contains("invis")?(info.skills.MailofHellfire=info.skills.MailofHellfireSource.blue,info.skills.Dereliction=info.skills.DerelictionSource.blue):(info.skills.MailofHellfire=info.skills.MailofHellfireSource.red,
info.skills.Dereliction=info.skills.DerelictionSource.red)})});weaponType.addEventListener("change",()=>{weaponSelect()});document.getElementById("weaponFilter").addEventListener("click",a=>{a.target.classList.toggle("blue");a.target.classList.toggle("gray");weaponSelect()});
document.querySelectorAll("input.check").forEach(a=>a.addEventListener("mousedown",b=>{/DemonDrug/.test(b?.target.id)&&("DemonDrug"===b?.target.id?document.getElementById("MegaDemonDrug").checked=!1:document.getElementById("DemonDrug").checked=!1);"filterCombo"!==b?.target.id?"WaterBlight"===b?.target.id&&(b=dropHZ.selectedIndex,monChart(),dropHZ.selectedIndex=b):b?.target===filterCombo&&filterTableForComboAttacks()}));
function toggleAmmoTables(){let a=document.getElementById("dpsTable").classList.contains("augInvis");document.getElementById("dpsTable").classList.toggle("augInvis",!a);document.getElementById("ammoTable").classList.toggle("augInvis",a)}
function calculateAmmoFrames(a){let b=/Sub-Lv|Explosion| Procs|\(RF\+\d\)/g.test(a.attackName)?a.attackName.replace(/Sub-| Explosion| \(RF\+\d\) Procs| Procs| \(RF\+\d\)/g,""):a.attackName;b=/(?<!Lv)\d/.test(b)?`${b.slice(0,b.length-1)}Lv${b.slice(-1)}`:b;const c={};c.ammoIncrease=info.ammo.AmmoUp[b][document.getElementById("AmmoUp").selectedIndex];c.recoilSpeed=info.ammo.recoil[b][Math.max(0,Math.min(5,a.recoil-1+document.getElementById("RecoilDown").selectedIndex+(0<info.skills.BowgunBarrel[document.getElementById("BowgunBarrel").selectedIndex??
0].Silencer?document.getElementById("Tune-Up").selectedIndex+info.skills.BowgunBarrel[document.getElementById("BowgunBarrel").selectedIndex??0].Silencer:0)-(0<document.getElementById("CriticalFirePower").selectedIndex?2:0)))];c.recoilSpeed=/\(RF\+\d\)/.test(a.attackName)?`${c.recoilSpeed} ${a.attackName.match(/\(RF\+\d\)/)[0]}`:c.recoilSpeed;c.recoilFrames=info.ammo.recoil.frames[c.recoilSpeed];c.reloadSpeed=info.ammo.reload[b][Math.max(0,Math.min(8,a.reload+document.getElementById("ReloadSpeed").selectedIndex+
info.skills.BowgunBarrel[document.getElementById("BowgunBarrel").selectedIndex??0].reload+(0===document.getElementById("BowgunBarrel")?.selectedIndex&&0<document.getElementById("Tune-Up").selectedIndex?1:0)-(0<document.getElementById("ElementalReload").selectedIndex?2:0)))];c.reloadFrames=info.ammo.reload.frames[c.reloadSpeed];c.clipSize=a.clipSize[a.isUsed]+c.ammoIncrease;c.spareShot=Math.max(0,info.skills.SpareShot[document.getElementById("SpareShot").selectedIndex]+Number(document.getElementById("spareAdjust").value));
/(?<!snipe.*)explosion/.test(b)&&0<document.getElementById("Bombardier").selectedIndex&&(c.spareShot+=info.skills.Bombardier[b.match(/Sticky|Wyvern/)[0]][2]);c.shotsPerMinBase=shotsCheck(c.recoilFrames/30,c.reloadFrames/30,a.clipSize[a.isUsed],60);c.shotsPerMin=shotsCheck(c.recoilFrames/30,c.reloadFrames/30,c.clipSize,60,100/c.spareShot);c.shotsPerGain=`${Number.parseFloat(100*(c.shotsPerMin/c.shotsPerMinBase-1)).toFixed(2)}%`;c.ticsAdjust=a.ticsPer+1;/Pierce Lv|Pierce [1-3]/.test(b)?c.ticsAdjust*=
JSON.parse(document.getElementById("pierceAdjust").value)[0]:/Pierc/.test(b)&&(c.ticsAdjust*=JSON.parse(document.getElementById("pierceAdjust").value)[1]);return c}
function comboReset(){document.getElementsByClassName("inputs").length&&!/BowGun/.test(document.getElementById("previousWeaponType").value)&&""!==document.getElementById("previousWeaponType").value&&(document.querySelectorAll(".comboHits").forEach(a=>a.remove()),document.querySelectorAll("#dpsBody>tr:nth-child(1)>td:nth-child(n+3)").forEach(a=>a.value=0),document.querySelectorAll(".inputs").forEach(a=>a.value=0),document.querySelectorAll(".inputComboRepeat").forEach(a=>a.value=1),comboTracker=[])}
function filterTableForComboAttacks(){document.querySelectorAll(".inputs").forEach((a,b)=>{/blue/.test(document.getElementById("filterCombo").className)&&(0==a.value||a.style.display.includes("none"))?document.getElementsByClassName([b]).style.display="none":document.getElementsByClassName([b]).style.display=""})}
info.augs={attackAug:[[0,0],[2,5],[4,10],[6,15],[8,20]],affinityAug:[[0,0],[3,5],[6,10],[8,15]],elementalAug:[[0,0],[1,0],[2,0],[3,0],[4,0],[5,0],[6,0],[7,0]],rampageAug:[[0,0],[3,1],[7,2]],sharpnessAug:[[0,0],[3,1],[5,2],[7,3]]};info.augIndex={attackAug:0,affinityAug:0,elementalAug:0,rampageAug:0,sharpnessAug:0};
document.getElementById("damageTable").addEventListener("mousedown",a=>{a.target.classList.contains("inputButton")&&(a.target?.classList.contains("dec")?decreaseComboCount(a):increaseComboCount(a),document.getElementById("comboCountContainer")?.classList.remove("augInvis"))});function increaseComboCount(a){20>Number(document.querySelectorAll(".inputs")[a?.target.id].value)&&(++document.querySelectorAll(".inputs")[a?.target.id].value,dataCompile())}
function decreaseComboCount(a){if("0"===a?.target.id&&1<Number(document.querySelectorAll(".inputs")[a?.target.id].value)||0<Number(a?.target.id)&&0<Number(document.querySelectorAll(".inputs")[a?.target.id].value))--document.querySelectorAll(".inputs")[a?.target.id].value,dataCompile()}
const quriousAugsDec=a=>{var b=+document.getElementById("weaponQurious").value.slice(-3,-2);let c=a.parentElement.querySelector("output.label"),d=info.augIndex[a.classList[0]];0!==d&&(b-=info.augs[a.classList[0]][d-1][0]-info.augs[a.classList[0]][d][0],d=--info.augIndex[a.classList[0]],c.textContent=info.augs[a.classList[0]][d][0],c.nextElementSibling.textContent="+"+info.augs[a.classList[0]][d][1],document.getElementById("weaponQurious").textContent=`Remaining Augments ${9-b}/9`)},quriousAugsInc=
a=>{let b=info.augIndex[a.classList[0]];if(info.augs[a.classList[0]][b+1]){var c=0;Object.entries(info.augs).forEach(([h,l])=>c+=l[info.augIndex[h]][0]);var d=c+(info.augs[a.classList[0]][b+1][0]-info.augs[a.classList[0]][b][0]);if(!(9<d)){var e=a.parentElement.querySelector("output.label");b=++info.augIndex[a.classList[0]];e.textContent=info.augs[a.classList[0]][b][0];e.nextElementSibling.textContent="+"+info.augs[a.classList[0]][b][1];document.getElementById("weaponQurious").textContent=`Remaining Augments ${9-
d}/9`}}};document.querySelectorAll(".augButton.inc").forEach(a=>a.addEventListener("mousedown",b=>quriousAugsInc(b.target)));document.querySelectorAll(".augButton.dec").forEach(a=>a.addEventListener("mousedown",b=>quriousAugsDec(b.target)));
function saveState(a=[[],[],[],[],[],[]]){document.getElementsByTagName("select").forEach(c=>{a[0].push(c.selectedIndex)});document.querySelectorAll("input.check").forEach(c=>{a[1].push(c.checked)});document.getElementsByClassName("inputs").forEach(c=>{a[2].push(c.value)});a[3].push(comboTracker);document.getElementsByClassName("scroll").forEach(c=>{a[4].push(c.className)});a[5]="";document.querySelectorAll("output.augLabel").forEach(c=>a[5]+=c.textContent);const b=document.createElement("input");
b.setAttribute("value",JSON.stringify(a));b.select();b.setSelectionRange(0,99999);navigator.clipboard.writeText(b.value);return a}
function loadState(a,b,c){b=document.querySelectorAll("select");b[0].selectedIndex=a[0][0];classChange();weaponSelect();for(c=0;c<a[5].length;c++)document.querySelectorAll("output.augLabel")[c].textContent=a[5][c];b[3].selectedIndex=a[0][3];rampageSelect();b[80].selectedIndex=a[0][document.querySelectorAll("select").length-10];document.getElementById("dropQuest").selectedIndex=1;partSelect();healthSelect();document.querySelectorAll("select").forEach((d,e)=>{0!==e&&3!==e&&e!==document.querySelectorAll("select").length-
10&&(d.selectedIndex=a[0][e])});document.querySelectorAll("input.check").forEach((d,e)=>{d.checked=a[1][e]});document.querySelectorAll(".inputs").forEach((d,e)=>{d.value=a[2][e]});document.querySelectorAll(".scroll").forEach((d,e)=>{d.className=a[4][e]});info.skills.MailofHellfire=document.querySelectorAll("#redScroll").classList.contains("invis")?info.skills.MailofHellfireSource.blue:info.skills.MailofHellfireSource.red;info.skills.Dereliction=document.querySelectorAll("#redScroll").classList.contains("invis")?
info.skills.DerelictionSource.blue:info.skills.DerelictionSource.red;[...comboTracker]=a[3][0];document.querySelectorAll("input:not(comboRepeat)").forEach(d=>{if(0<d.value){let e=document.querySelectorAll(".inputs")[d.id]?.value??0-timesUsed(d.id);for(;0<e;)comboTracker.push(d.id),--e;for(;0>e;)comboTracker.splice(comboTracker.lastIndexOf(d.id),1),++e}});updateComboDisplay()}function weaponTypeSelect(){populateDropDowns(weaponTypes,weaponType)}
document.querySelectorAll("#weaponFilter,button.rampageAug").forEach(a=>a.addEventListener("click",()=>{rampageSelect()}));
function weaponSelect(){Object.values(dropWeapon.children).forEach(b=>b.remove());let a=[];a=document.getElementById("weaponFilter").className.includes("blue")?Object.entries(info[weaponType.value].weapons).filter(b=>10===b[1].rank):Object.entries(info[weaponType.value].weapons);a.forEach(b=>{const c=document.createElement("option");c.value=b[0];c.textContent=b[1].weapon;dropWeapon.append(c)})}
function rampageSelect(){const a=[],[...b]=getWeaponMR().decos;b.forEach((c,d)=>{0<c&&a.push(d+1);1<b[d-1]?a.push(d):1<b[d+1]?(a.push(d+2),--b[d+1]):2<b[d-2]?(a.push(d-1),--b[d-2]):2<b[d+2]&&(a.push(d+3),--b[d+2])});setDecoDisplay("weapon",a.reverse());document.querySelectorAll("#weaponRampage>*").forEach(c=>c.style.display="none");document.getElementById("weaponRampage0").style.display="";if(getWeaponMR().rampageSlots){const c=[];document.getElementById("rampImg").src=document.getElementById("rampImg").src.replace(/ramp\d/,
`ramp${Math.min(3,getWeaponMR().rampageSlots+info.augIndex.rampageAug)}`);Object.keys(info.rampage.rampageDecos).forEach(d=>{Number(d.slice(-1))<=Math.min(3,getWeaponMR().rampageSlots+info.augIndex.rampageAug)&&c.push(info.rampage.rampageDecos[d])});populateDropDowns(c,document.getElementById("weaponRampage0"))}else document.querySelectorAll("#weaponRampage>*").forEach(c=>{c.selectedIndex=0;c.style.display="none"}),document.getElementById("weaponRampage0").style.display="",/Rampage/.test(getWeaponMR().weapon)?
info.rampage[getWeaponMR().weapon].Rampage.forEach((c,d)=>{document.querySelector("#weaponRampage").children[d].style.display="";populateDropDowns(Object.values(c),document.querySelector("#weaponRampage").children[d])}):getWeaponMR().rampage.forEach(c=>{const d=document.createElement("option");d.value=info.rampage.keys2[c];d.textContent=info.rampage.keys2[c];document.getElementById("weaponRampage0").append(d)})}
function populateDropDowns(a,b,c=a){b?.childElementCount&&Object.values(b.children).forEach(d=>d.remove());a.forEach((d,e)=>{const h=document.createElement("option");h.value=c[e];h.textContent=d;b.append(h)})}function monsterSelect(){populateDropDowns(Object.keys(info.monster),dropMon);dropMon.selectedIndex=Object.keys(info.monster).indexOf("Toadversary")}const getEleHZ=a=>info.monster[dropMon.value].parts[dropHZ.selectedIndex][lower(a)];
function getRawHZ(a){return void 0===info.monster[dropMon.value].parts[dropHZ.selectedIndex][lower(a)]?100:document.getElementById("WaterBlight").checked?Math.min(100,~~(Math.max(info.monster[dropMon.value].parts[dropHZ.selectedIndex][lower(a)],.63*info.monster[dropMon.value].parts[dropHZ.selectedIndex][lower(a)]+22.2)+3)):info.monster[dropMon.value].parts[dropHZ.selectedIndex][lower(a)]}
const getUsedAttacks=(a=weaponType.value)=>{let b={};if("InsectGlaive"===weaponType.value)return b=Object.fromEntries(Object.entries(info.InsectGlaive.attacks).filter(c=>!/Sever|Blunt|Kinsect|Dust|Powder|Mark/.test(c))),{...b};if("ChargeBlade"===weaponType.value){a="Impact Phial"===getWeaponMR().phialType?"Element Phial|Elemental Phial":"Impact Phial";const c=new RegExp(`${a}`);b=Object.fromEntries(Object.entries(info.ChargeBlade.attacks).filter(d=>!c.test(d)));return{...b}}if("Bow"===weaponType.value){let c=
"";const d=1===document.getElementById("BowChargePlus").selectedIndex&&4>getWeaponMR().baseCharge?getWeaponMR().baseCharge+1:getWeaponMR().baseCharge;getWeaponMR().bowShot.forEach((h,l)=>{l<d&&(c+=`|Lv${h.match("[1-5]")[0]} ${h.match("Normal|Rapid|Pierce|Spread")[0]}`)});const e=new RegExp([c.slice(1)]);a=Object.entries(info.Bow.attacks).filter(h=>e.test(h[0]));a=[].concat(Object.entries(info.Bow.attacks).splice(0,1),a);a=a.concat(Object.entries(info.Bow.attacks).splice(136));b=Object.fromEntries(a);
return{...b}}if("Gunlance"===weaponType.value)return b=Object.fromEntries(Object.entries(info.Gunlance.attacks).splice(0,27)),{...b};if("LightBowGun"===weaponType.value||"HeavyBowGun"===weaponType.value){let c=info.ammo.keys.map((d,e)=>d.filter(h=>"LightBowGun"===weaponType.value&&getWeaponMR().isRapidFire.includes(e+1)?/RF\+/.test(h):0<getWeaponMR().clipSize[e+1]&&!/RF\+/.test(h))).toString().split(/,+/);c=c.concat(Object.keys(info.ammo).filter(d=>"LightBowGun"===weaponType.value?/lbg|Wyvern Blast(?! before)/.test(d):
/hbg|Wyverns/.test(d)));b=Object.fromEntries(Object.entries(info.ammo).filter(d=>0<timesUsed(d[0],c)));return{...b}}return{...info[a].attacks}},getAttacks=(a=weaponType.value)=>({...info[a].attacks}),getWeapon=()=>0<info[weaponType.value].weapons[dropWeapon.selectedIndex].rampageSlots?getWeaponMR():getRampageSkills();
function partSelect(){document.querySelectorAll("#dropHZ>option").forEach(b=>b.remove());const a=[];info.monster[dropMon.value].parts.forEach(b=>{a.push([`${b.part} ${b.state}`])});populateDropDowns(a,dropHZ)}
function questSelect(){document.querySelectorAll("#HR>option").forEach(a=>a.remove());document.querySelectorAll("#MR>option").forEach(a=>a.remove());Object.values(info.quest).filter(a=>{if(a.target.some(b=>b.name===dropMon.selectedOptions[0].textContent))return a}).forEach(a=>{a.target.forEach((b,c)=>{b.name===dropMon.value&&(b=document.createElement("option"),b.value=a.quest,b.textContent=a.quest,document.getElementById(a.rank).append(b))})});updateQuest(0<document.querySelectorAll("#MR>option")?.length?
document.querySelectorAll("#MR>option")[0].textContent:document.querySelectorAll("#HR>option")[0].textContent);document.querySelectorAll("MR>option")?.length?document.getElementById("MR")?.classList.remove("augInvis"):document.getElementById("MR")?.classList.add("augInvis");document.querySelectorAll("HR>option")?.length?document.getElementById("HR")?.classList.remove("augInvis"):document.getElementById("HR")?.classList.add("augInvis")}
function healthSelect(){let a=1;switch(document.getElementById("players").selectedOptions[0].value){case "1p":a=1;break;case "2p":a=1.35;break;case "3p":a=1.7;break;case "4p":a=2}info.quest[dropQuest.value].target.forEach(b=>{b.name===dropMon.value&&(b=b.hp.map(c=>c*a),populateDropDowns(b,document.getElementById("health")))})}function isUnique(a,b,c){return c.indexOf(a)===b}
function showMenu(){document.querySelectorAll(".menu").forEach(b=>b.classList.remove("augInvis"));var a=0<document.querySelectorAll("#MR>option").length;document.getElementById("MR").parentElement.classList.toggle("augInvis",!a);a=0<document.querySelectorAll("#HR>option").length;document.getElementById("HR").parentElement.classList.toggle("augInvis",!a)}
function updateQuest(a){document.getElementById("dropQuest").selectedOptions[0].value=a;document.getElementById("dropQuest").selectedOptions[0].textContent=a;document.getElementById("questDiv")?.classList.add("augInvis")}const capitalAll=a=>a.replace(/(?<!\w)\w/g,b=>b.toUpperCase()),capital=(a,b=0)=>a[b].toUpperCase()+a.slice(1),lower=a=>a[0].toLowerCase()+a.slice(1);
function shotsCheck(a,b,c,d=60,e=0){let h;h=0+e;let l=0,k=0;for(;l<=d;){for(let f=0;f<c;++f)l+=a,k+=l<=d?1:0,k>=h&&0!==e&&Infinity!==e&&(--f,h+=e);l+=b}return k}function getHealthPools(a=[[],[],[],[]]){info.quest.filter(b=>b.quest===dropQuest.value).target[dropMon.value].hp.forEach(b=>{a[0].push(b);a[1].push(~~(1.35*b));a[2].push(~~(1.7*b));a[3].push(~~(2*b))});return a}
function resetSkillDescription(){if(""!==lastEvent&&(lastEvent!==document.getElementById("BowCoating")||"Bow"===weaponType.value)){var a=[];Object.values(lastEvent.children).some(b=>"OPTGROUP"===b.tagName)?(a=document.querySelectorAll(`${lastEvent.id}>*>*`),a.splice(-2),a.splice(0,0,lastEvent[0])):a=Object.values(lastEvent.children);a.forEach((b,c)=>{if(lastEvent===document.getElementById("BowCoating"))var d=getWeaponMR().coatings[c];else lastEvent===document.getElementById("BowgunBarrel")?d=["----",
"Long","Power","Silencer","Guard-Up"][c]:lastEvent===document.getElementById("Dereliction")?d="---- Lv-1-1 Lv-1-2 Lv-1-3 Lv-2-1 Lv-2-2 Lv-2-3 Lv-3-1 Lv-3-2 Lv-3-3".split(" ")[c]:(d=c+0,"OPTGROUP"===lastEvent.children[1].tagName&&0!==c&&(d="Burst"===lastEvent.id&&2<=c?c-1:0===c%3?3:c%3),d="Burst"===lastEvent.id&&1===c?"Base Bonus":`Lv-${d}`);b.textContent=0===c?"----":d});lastEvent=""}}
document.querySelectorAll(".buildSkills").forEach(a=>a.addEventListener("mousedown",b=>{if(""===lastEvent||lastEvent!==b?.target||b.target.className.includes("augment"))""!==lastEvent&&resetSkillDescription(),b.target.classList.contains("skill")&&setSkillDescriptions(b?.target),"INPUT"===b.target.tagName&&b.target.className.includes("skillInput")&&(lastEvent=b.target)}));document.querySelectorAll("select.skill").forEach(a=>a.addEventListener("change",b=>{resetSkillDescription();b?.target.blur()}));
function setSkillDescriptions(a){a.classList.contains("skill")&&Array.isArray(info.skills[a.id])&&(info.skills[a.id].forEach((b,c)=>{if(0!==c)if("RecoilDown"===a.id||"ReloadSpeed"===a.id)var d=`${a.id.slice(0,6)} ${a.id.slice(6)} +${c}`;else if("AmmoUp"===a.id||"SpareShot"===a.id)d=`${c}: ${("AmmoUp"===a.id?["No Change","Lv2 & Ele Ammo","Lv3 & Dragon Ammo"]:["Spare Shot +5%","Spare Shot +10%","Spare Shot +20%"])[c-1]}`;else if("Marksman"===a.id)d=`${c}: ${["Chance 20% Raw  + 5% EFR +1%","Chance 20% Raw+10% EFR +2%",
"Chance 60% Raw  + 5% EFR +3% ","Chance 40% Raw+10% EFR +4%"][c-1]}`;else if("Bombardier"===a.id)d="HeavyBowGun"!==weaponType.value?`${c}: Raw +${info.skills.Bombardier[c][0]}% EFR +${info.skills.Bombardier[c][1]}`:["Bombardier","1: Raw + 10% EFR + 10%","2: Sticky+10% Wyvern+15%","3: Raw + 20% EFR + 16%","4: Raw + 25% EFR + 17%"][c];else if("BowgunBarrel"===a.id)d=["Barrels","Long: Raw + 5%","Power: Raw + 12.5%","Silencer: Recoil Down +1","Shield: Guard Up"][c];else if("CriticalFirePower"===a.id)d=
["-","Normal +30% Spread +20% Pierce +10% Recoil -2"][c];else{d="";if(0<b.BR||1<b.PRM||1<b.BRM){d="Raw";0<b.BR&&(d+=/\d\.?\d/.test(b.BR)?`+${b.BR}`:` + ${b.BR}`);if(1<b.BRM){var e=/\.[1-8]/.test(100*(b.BRM-1))?(100*(b.BRM-1)).toFixed(1):(100*(b.BRM-1)).toFixed(0);d+=/\d\.?\d/.test(e)?`+${e}%`:` + ${e}%`}1<b.PRM&&(e=/\.[1-8]/.test(100*(b.PRM-1))?(100*(b.PRM-1)).toFixed(1):(100*(b.PRM-1)).toFixed(0),d+="CriticalBoost"===a.id&&/\d\.?\d/.test(e-25)?`+${e-25}%`:"CriticalBoost"===a.id?` + ${e-25}%`:/\d\.?\d/.test(e)?
`+${e}%`:` + ${e}%`)}e="";if(0<b.BE||1<b.PEM||1<b.BEM){e="Ele";0<b.BE&&(e+=/\d\.?\d/.test(b.BE)?`+${b.BE}`:` + ${b.BE}`);if(1<b.BEM){var h=/\.[1-8]/.test(100*(b.BEM-1))?(100*(b.BEM-1)).toFixed(1):(100*(b.BEM-1)).toFixed(0);e+=/\d\.?\d/.test(h)?`+${h}%`:` + ${h}%`}1<b.PEM&&(h=/\.[1-8]/.test(100*(b.PEM-1))?(100*(b.PEM-1)).toFixed(1):(100*(b.PEM-1)).toFixed(0),e+=/\d\.?\d/.test(h)?`+${h}%`:` + ${h}%`)}h=0<b.aff&&/\d\.?\d/.test(b.aff)?`Aff+${b.aff}`:0<b.aff?`Aff + ${b.aff}`:"";d=Object.prototype.hasOwnProperty.call(b,
"Sharp")&&1>b.Sharp?`Sharp +${100*b.Sharp}%`:d;d=Object.prototype.hasOwnProperty.call(b,"Sharp")&&1<b.Sharp?`Sharp +${b.Sharp}`:d;d=""===d&&""===e&&""===h?"No Change":d;a===document.getElementById("BowCoating")?d=`${getWeaponMR().coatings[c]}: ${[d,e,h].join(" ")}`:(b=c+0,"OPTGROUP"===a.children[1].tagName&&0!==c&&(b="Burst"===a.id&&2<=c?c-1:0===c%3?3:c%3),d=`${b}: ${[d,e,h].join(" ")}`)}else d=a.id;info.description||(info.description={});info.description[a.id]||(info.description[a.id]=[]);info.description[a.id].push(d);
document.getElementById(a.id)[c].textContent=d}),lastEvent=a)}function getStats(a){a.getSkills.forEach(b=>{a.BRM*=+b.BRM;a.BR+=+b.BR;a.PRM*=+b.PRM;a.BEM*=+b.BEM;a.BE+=+b.BE;a.PEM*=+b.PEM;a.aff+=+b.aff});return{...a}}function partSelector(){document.querySelectorAll("dropHZ>*").forEach((a,b)=>{a.textContent===getWeapon().eleType&&(document.getElementById("dropHZ").selectedIndex=b)})}function formatNumbers(a){return a.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g,"$1,")}
const createSkillSelections=(a,b=0,c)=>{if("Skill Selector"!==a)if(null!==document.getElementById(`${a}Select`))document.getElementById("dropSkills").after(document.getElementById(`${a}Select`));else{c=document.createElement("div");var d=document.createElement("label");d.className=`label ${a} skillInput`;d.textContent=a;var e=document.createElement("output");e.className=`skillInput ${a}`;e.setAttribute("max",info.types.maxLevel[a]);e.setAttribute("min","0");e.textContent=`Lv-${b}`;b=document.createElement("button");
b.type="button";b.setAttribute("aria-pressed","false");b.id=`${a}Dec`;b.className=`skillInput ${a} dec`;b.title+="Decrease Skill Level";b.innerHTML+="&#8681";var h=document.createElement("button");h.type="button";h.setAttribute("aria-pressed","false");h.id=`${a}Inc`;h.className=`skillInput ${a} inc`;h.title+="Increase Skill Level";h.innerHTML+="&#8679";c.appendChild(d);c.appendChild(e);c.appendChild(b);c.appendChild(h);c.id=`${a}Select`;document.getElementById("dropSkills").after(c)}},getSkillSelects=
()=>{document.querySelectorAll("select.skill").forEach(a=>{0<a.selectedIndex&&createSkillSelections(a.id,a.selectedIndex)})};document.getElementById("dropSkills")?.addEventListener("change",a=>{document.getElementById(a.target.value)?.className.includes("classSpecific")&&!document.getElementById(a.target.value)?.className.includes(weaponType.value)||createSkillSelections(a.target.value,info.types.maxLevel[a.target.value])});document.getElementById("otherButton").addEventListener("click",()=>{document.getElementById("boxes").classList.toggle("augInvis")});
document.querySelector(".boxes.close").addEventListener("click",()=>{document.getElementById("boxes").classList.add("augInvis");document.getElementById("otherButton").checked=""});document.getElementById("dangoSkillsButton").addEventListener("click",()=>{document.getElementById("dango").classList.toggle("augInvis")});
document.querySelector(".dango.close").addEventListener("click",()=>{document.getElementById("dango")?.classList.add("augInvis");document.getElementById("dangoSkillsButton").checked=""});document.getElementById("uniqueSkillsButton").addEventListener("click",()=>{document.getElementById("unique").classList.toggle("augInvis")});
document.querySelector(".unique.close").addEventListener("click",()=>{document.getElementById("unique").classList.add("augInvis");document.getElementById("uniqueSkillsButton").checked=""});document.getElementById("quriousButton").addEventListener("click",()=>{document.querySelectorAll(".armorAugment").forEach(a=>a.classList.toggle("augInvis"))});
document.getElementById("extraCharmDeco").addEventListener("click",()=>{document.querySelector("select.charmSlot3").classList.toggle("armorDisplay");document.querySelector("select.charmSlot3").selectedIndex=(document.querySelector("select.charmSlot3").classList.contains("armorDisplay"),0);document.querySelectorAll(".charmSlot3").forEach(a=>a.classList.toggle("augInvis"))});
document.getElementById("skillSelect").addEventListener("mousedown",a=>{if(a.target.classList.contains("skillInput")){const b=a.target.className.split(" ")[1];let c=+document.querySelector(`output.${b}`)?.textContent.match(/(?<=Lv-)\d/)[0];"BUTTON"===a.target.tagName&&(a.target.classList.contains("dec")?0===c?a.target.parentElement.remove():document.querySelector(`output.${b}`).textContent=`Lv-${c-1}`:a.target.classList.contains("inc")&&(document.querySelector(`output.${b}`).textContent=`Lv-${c<info.types.maxLevel[b]?
c+1:c}`));document.getElementById("chest")}});
const addPoints=([a,b])=>{const c=document.querySelector(`output.${a}`);c?c.textContent=`Lv-${Math.min(info.types.maxLevel[a]||info.skills[a].length-1,c.textContent.slice(-1)+ +b)}`:createSkillSelections(a,b)},getCurrentArmorSkills=(a={})=>{Object.keys(info.armor).forEach(b=>{Object.values(document.querySelectorAll(`#${b}Skills>output`)).forEach(c=>{const d=c.value?.split(" ")[0].split("\n")[0];(c=+c.value.slice(-2))&&(a[d]=a[d]?a[d]+c:c)})});return a},getCurrentSelectedSkills=(a={})=>{Object.values(document.querySelectorAll("select.armorDisplay,select.charm")).map(b=>
{const c=b.selectedOptions[0].textContent?.slice(0,-3).trim();b=+b.selectedOptions[0].textContent?.slice(-2);0<b&&(a[c]=a[c]?a[c]+b:b)});return a},updateSelectedSkills=()=>{let a=getCurrentSelectedSkills();a=getCurrentArmorSkills(a);document.querySelectorAll("#raw select").forEach(b=>b.selectedIndex=a[b.id]?Math.min(a[b.id],info.types.maxLevel[b.id]?info.types.maxLevel[b.id]:info.skills[b.id].length-1):0);return a};
function armorSelect(){info.armor&&Object.entries(info.armor).forEach(a=>{let b="";const c=document.getElementById(a[0]);a[1].forEach((d,e)=>b+=`<option value=${e}>${d.name}</option>`);c.innerHTML=b})}
const resetPoints=(a,b)=>{Object.values(document.querySelectorAll(`#${a.id}>select`)).forEach(c=>c.selectedIndex=-1);getRemainingPoints(a)},hideShowMenu=a=>{const b=a.className.split(" ")[0];a.className.includes("inc")?document.getElementById(`${b}Qurious`)?.classList.remove("augInvis"):document.getElementById(`${b}Qurious`).classList.add("augInvis")},setCharmsAvailableDecoSlots=a=>{var b=document.getElementById(1===+a.id.slice(-1)?`${a.id.slice(0,-1)}2`:`${a.id.slice(0,-1)}1`);a.selectedOptions[0].textContent.slice(0,
-3)===b.selectedOptions[0].textContent.slice(0,-3)&&(b.selectedIndex=0);const c=[];b=getGrade(b?.value,a.value);if(b!==document.getElementById(`${a.id.slice(0,5)}Decos`).value){document.getElementById(`${a.id.slice(0,5)}Decos`).value=b;switch(b){case "S":c.push(2,1,1);break;case "A":c.push(3,1,1);break;default:c.push(3,2,1)}setDecoDisplay(a.id.slice(0,5),c)}},getArmor=a=>{for(let b=0;b<info.armor[a].length;b++)if(info.armor[a][b].name.includes(document.getElementById(a).selectedOptions[0].textContent))return info.armor[a][b]},
getRemainingPoints=(a,b=0)=>{var c=a.id.slice(0,-7);c=getArmor(c);b+=c.quriousPoints;for(let d=0;6>d;d++){const e=document.querySelectorAll(`#${a.id}>select.augment`)[d];0>b+ +e.value&&(e.selectedIndex=0,document.querySelectorAll(`#${a.id}>select.augmentType`)[d].selectedIndex=0);b+=+e.value}a.firstElementChild.textContent=`Remaining Points ${`${b}/${c.quriousPoints}`}`;return b},setArmorSkillsDisplay=(a=Object.keys(info.armor))=>{Object.values(a).forEach(b=>{if(""!==b){var c=document.getElementById(b);
if(c){var d=getArmor(b);const h=[],[...l]=d.decos;l.forEach((g,m)=>{0<g&&h.push(m+1);1<l[m-1]?h.push(m):1<l[m+1]?(h.push(m+2),--l[m+1]):2<l[m-2]?(h.push(m-1),--l[m-2]):2<l[m+2]&&(h.push(m+3),--l[m+2])});h.reverse();const k=document.querySelectorAll(`#${b}Qurious>select.augmentType`),f=document.querySelectorAll(`#${b}Qurious>select.augment`);d=JSON.parse(JSON.stringify(d.skills));for(let g=0;6>g;++g)if(1<f?.length&&0<f[g].selectedIndex&&(2===k[g].selectedIndex||4===k[g].selectedIndex)){var e=f[g].selectedOptions[0].textContent.match(/^\S+/)[0];
d[e]=d[e]?d[e]+(k[g].selectedIndex-3):1}else if(1<k?.length&&0<f[g].selectedIndex&&3===k[g].selectedIndex){e=f[g].selectedIndex;for(let m=0,n=-1;0<e&&3>n;)if(2>n&&!h[n+1]&&(h[n+1]=0),0===m)3===++n?(m=1,n=0):0===h[n]&&(++h[n],--e);else{if(1===m&&4>h[n]){const p=Math.min(e,4-h[n]);h[n]+=p;e-=p}++n}}c.nextElementSibling.textContent="";Object.entries(d).forEach(g=>c.nextElementSibling.innerHTML+=`<img class="armorImg armorDeco rampage" src="./icons/skill.png"><output>${g[0].match(/^\S+/)[0]} +${g[1]}</output>`);
c.nextElementSibling.id=`${b}Skills`;setDecoDisplay(b,h)}}})},ChangeDropdownOptions=a=>{var b=a.classList.contains("augmentType")?a:a.previousElementSibling;const c=a.classList.contains("augmentType")?a.nextElementSibling:a;var d=a.parentElement.id.slice(0,-7);const e=c.selectedIndex;for(;c.firstChild;)c.removeChild(c?.firstChild);var h=document.createElement("option");h.value=0;h.textContent=" ---- ";c.appendChild(h);const l=getRemainingPoints(a.parentElement);switch(b.value){case "-Def":for(b=0;2>=
b;++b)d=document.createElement("option"),d.value=[3,5][b],d.textContent=["-6 Def +3 Pts","-12 Def +5 Pts"][b],c.appendChild(d);break;case "-Skill":document.querySelectorAll(`#${d}Skills>output`).forEach(f=>{const g=document.createElement("option");g.value=10;g.textContent=`${f.textContent.split("\n")[0].split(" ")[0]} 10`;g.classList.toggle("augInvis",0>=+f.textContent.slice(-2));c.appendChild(g)});break;case "+Skill":const k=document.querySelectorAll(`#${d}Skills>output`);Object.entries(info.types.qurious).forEach(f=>
{const g=document.createElement("option");g.value=-f[1];g.textContent=`${f[0]} -${f[1]}`;g.classList.toggle("augInvis",f[1]>l||5<=k.length&&!Object.values(k).some(m=>m.textContent.includes(f[0])));c.appendChild(g)});break;case "+Slots":for(b=1;3>=b;b++)d=-6*b,h=document.createElement("option"),h.value=d,h.textContent=`+${b} Slot${1!==b?"s":""} ${d}Pts`,h.classList.toggle("augInvis",l<d),c.appendChild(h)}a.className.includes("Type")?c.selectedIndex=0:c.selectedIndex=e},updateAugmentOptions=a=>{var b=
a.classList.contains("augmentType")?a:a.previousElementSibling;const c=a.classList.contains("augmentType")?a.nextElementSibling:a;a=a.parentElement.id.slice(0,-7);const d=getRemainingPoints(c.parentElement),e=Object.values(document.querySelectorAll(`#${a}Skills>output`));switch(b.value){case "-Skill":e.forEach((h,l)=>{c.children[l+1]&&(h=0>=+h.textContent.split(" ")[1]&&l+1!==c.selectedIndex,c.children[l+1]?.classList.toggle("augInvis",h),c.children[l+1].disabled=h)});break;case "+Slots":for(b=1;3>=
b;b++)a=d-(isNaN(+c.value)?0:+c.value)<[0,6,12,18][b],c.children[b].classList.toggle("augInvis",a),c.children[b].disabled=a;break;case "+Skill":Object.values(c.children).forEach(h=>{let l=0<=+h.value+(d-(isNaN(+c.value)?0:+c.value))&&(5>e.length||e.some(k=>k.textContent.includes(h.textContent.split(" ")[0])));h.classList.toggle("augInvis",!l);h.disabled=!l})}},setDecoDisplay=(a,b)=>{if("charm"===a)document.querySelectorAll(`section.${a} .decoDisplay img`).forEach((c,d)=>{const e=c.nextElementSibling;
c.src=`./icons/Lvl${b[d]}.png`;Object.values(e.children).forEach(h=>{if(h.value){const [l]=h.value.split(".");l>b[d]?(h.style.display="none",h.disabled=!0):(h.style.display="block",h.disabled=!1)}});e.selectedIndex=0});else{const c=document.createElement("section");c.className="decoDisplay";const d=document.querySelector(`#${a}Decos`),e=Object.values(d?.children).map(h=>h.selectedIndex);b.forEach((h,l)=>{l=document.createElement("img");l.classList.add("armorImg","armorDeco",`lvl${h}`);l.src=`./icons/Lvl${h}.png`;
c.appendChild(l);const k=document.createElement("select");k.classList.add("armorDisplay");l=document.createElement("option");l.textContent=" ---- ";k.appendChild(l);let f=4;for(;-1<--f;)l=document.createElement("Option"),l.classList.add("optTitle"),l.textContent=`Lvl-${f+1} Decos`,h<=f&&(l.style.display="none",l.disabled=!0),k.appendChild(l),Object.values(info.types.decoLevels[f]).forEach(g=>{const m=document.createElement("option");m.value=`${f+1}`;m.textContent=`${Object.keys(g)} +${Object.values(g)}`;
h<=f&&(m.style.display="none",m.disabled=!0);k.appendChild(m)});c.appendChild(k)});d?.replaceWith(c);c.id=`${a}Decos`;Object.values(document.querySelector(`#${a}Decos`).children).map((h,l)=>{h.childElementCount&&e[l]&&(h.selectedIndex="none"!==h.children[e[l]]?.style.display?e[l]:0)})}document.querySelectorAll(`section.${a} .decoDisplay img`).forEach((c,d)=>{const e=c.nextElementSibling;c.src=`./icons/Lvl${b[d]}.png`;Object.values(e.children).forEach(h=>{if(h.value){const [l]=h.value.split(".");l>
b[d]?(h.style.display="none",h.disabled=!0):(h.style.display="block",h.disabled=!1)}});e.selectedIndex=0})},getDrugIndex=a=>Object.values(document.getElementById("comboCountDisplay").children).indexOf(a);document.addEventListener("dragstart",a=>{a.dataTransfer.setData("text/plain",getDrugIndex(a.target))});document.addEventListener("dragover",a=>{a.preventDefault();a.dataTransfer.dropEffect="move"});
document.addEventListener("drop",a=>{a.preventDefault();const b=a.dataTransfer?.getData("text/plain");"comboCountDisplay"===a.target.parentElement.id&&a.target.before(Object.values(a.target.parentElement.children)[+b]);comboTracker=Object.values(document.getElementById("comboCountDisplay").children).map(c=>c.className.split(" ")[0])});
const validator=(a,b=0)=>{const c=a.id.slice(0,-7);setArmorSkillsDisplay([c]);const d=getArmor(c);Object.values(document.querySelectorAll(`#${c}Skills>output`)).map(e=>{0>+e.textContent.slice(-2)&&Object.values(document.querySelectorAll(`#${c}Qurious>select.augment`)).filter(h=>!h.selectedOptions[0]?.textContent.includes(e.textContent.slice(0,-4)))}).forEach(e=>{e&&(e[e.length-1].selectedIndex=-1,e[e.length-1].previousSibling.selectedIndex=-1,setArmorSkillsDisplay([c]))});b+=d.quriousPoints;for(let e=
0;6>e;e++){const h=document.querySelectorAll(`#${a.id}>select.augment`)[e];0>b+ +h.value&&(h.selectedIndex=-1,document.querySelectorAll(`#${a.id}>select.augmentType`)[e].selectedIndex=-1);b+=+h.value}a.firstElementChild.textContent=`Remaining Points ${`${b}/${d.quriousPoints}`}`;return b};
Object.values(document.querySelectorAll(".augmentType, .augment")).forEach(a=>a.addEventListener("change",b=>{b.stopPropagation();b.target?.className.includes("augment")&&(b.target.classList.contains("augmentType")?ChangeDropdownOptions(b.target):updateAugmentOptions(b.target),validator(b.target.parentElement),setArmorSkillsDisplay([b.target.parentElement.id.slice(0,-7)]),updateSelectedSkillsDisplay())}));
document.querySelectorAll("button").forEach(a=>a.addEventListener("click",b=>{"startSearch"!==b.target.id&&"searchAgain"!==b.target.id&&"extendedSearch"!==b.target.id&&dataCompile(b)}));document.querySelectorAll("select,input").forEach(a=>a.addEventListener("change",b=>dataCompile(b)));const resetAugmentSelections=a=>{document.querySelectorAll(`#${a}Qurious select`).forEach(b=>b.selectedIndex=b.classList.contains("augmentType")?0:-1);updateSelectedSkills()};
document.querySelectorAll("section.armorDisplay").forEach(a=>a.addEventListener("change",b=>{"SELECT"===b.target.tagName&&updateSelectedSkillsDisplay()}));
document.querySelectorAll("select.augment,select.augmentType").forEach(a=>{a.addEventListener("mousedown",b=>{b.target.classList.contains("augmentType")||updateAugmentOptions(b.target);1>b.target.previousElementSibling?.selectedIndex?Object.values(b.target.children).forEach(c=>c.disabled=!0):Object.values(b.target.children).forEach(c=>c.disabled=!1);updateSelectedSkillsDisplay()})});
document.querySelectorAll("select.armor").forEach(a=>{a.addEventListener("change",b=>{b=b.target.className.split(" ")[0];const c=getArmor(b);document.querySelector(`section#${b}Qurious>output.currentPoints`).textContent=`Remaining Points ${c.quriousPoints}/${c.quriousPoints}`;setArmorSkillsDisplay([b])})});document.querySelectorAll("input, button:not(#setReturn button), select:not(#setReturn select)").forEach(a=>{a.addEventListener("change",()=>updateSelectedSkills(a))});
document.querySelector("#weaponSelects>#Qurious")?.addEventListener("mousedown",()=>{document.getElementById("augToggle")?.classList.remove("augInvis")});setTimeout(function(){document.querySelectorAll("option").forEach(a=>{a.disabled="none"===a.style.display})},100);weaponType.addEventListener("change",()=>{weaponSelect();classChange();rampageSelect();monChart();partSelector();comboReset()});dropWeapon.addEventListener("change",()=>rampageSelect());
document.querySelectorAll("select.menu").forEach(a=>a.addEventListener("change",b=>{updateQuest(b.target.selectedOptions[0].value);monChart();healthSelect()}));document.getElementById("players")?.addEventListener("change",()=>healthSelect());dropQuest.addEventListener("change",()=>{monChart();healthSelect()});dropMon.addEventListener("change",()=>{partSelect();questSelect();healthSelect();monChart()});document.querySelector("#questButton").addEventListener("mousedown",()=>showMenu());
Object.values(document.querySelectorAll("#searchAgain, #startSearch")).forEach(a=>a.addEventListener("click",()=>getSetBuilds(12)));Object.values(document.querySelectorAll(".armorImg+.charm")).forEach(a=>a.addEventListener("change",b=>setCharmsAvailableDecoSlots(b.target)));document.querySelector(".extraSkills").addEventListener("mousedown",a=>{"BUTTON"===a.target.tagName&&addPoints(a.target.textContent.split(" +"))});
document.querySelector(".grid").addEventListener("mousedown",a=>{if("BUTTON"===a.target.tagName){let b=Object.values(document.querySelectorAll("div.grid > div.setResult")).indexOf(a.target.parentElement);a=GlobalMap.get(b)[a.target.parentElement.lastElementChild.selectedIndex];let c={};a.usedSkills.slice(-2).forEach(e=>c[e[0]]=e[1]);equipBuild(a,c);const d={};a.usedSkills.forEach(e=>{const h=e[3]?e[1]*e[3]:e[1];d[e[0]]=d[e[0]]?d[e[0]]+h:h});console.log({build:a,charm:c,buildTest:d});document.getElementById("setReturn").classList.add("augInvis");
dataCompile();document.querySelectorAll(".extraSkills>button").forEach(e=>e.remove());document.querySelectorAll(".grid>div").forEach(e=>e.remove());GlobalMap.clear()}});let newSkills={},totalCombos=0,timer=0,GlobalMap=new Map,workers=[],workerCount=0,GlobalFragment=document.createDocumentFragment(),totalSets=0;
const getUsedDecoArr=a=>{const b=[[],[],[],[]];for(let c=0;c<a.length;c++)if(a[c][2]&&a[c][2]?.includes("Slot lvl")){const d=+a[c][2].slice(-1);let e=a[c][3];for(;0<=--e;)b[d-1].push(a[c][0])}return b},setAugmentAuto=(a,b)=>{let c=0;a.augs.forEach(d=>{var e=b[c];let h=e.nextElementSibling,[l,k]=Object.entries(d)[0],f=0;Object.values(h.children).forEach(g=>g.remove());h.innerHTML+='<option value="0"> ---- </option>';switch(l){case "-Def":e.selectedIndex=1;for(d=3;5>=d;d+=2)e=document.createElement("option"),
e.value=d,e.textContent=3===d?"-6 Def +3 Pts":"-12 Def +5 Pts",h.appendChild(e);h.selectedIndex=2;break;case "-Skill":e.selectedIndex=2;for(let g=0,m=document.querySelectorAll(`#${a.type}Skills>output`);g<m.length;g++)m[g].textContent.includes(k)&&(f=g),d=document.createElement("option"),d.value=10,d.textContent=`${k} +10Pts`,h.appendChild(d);h.selectedIndex=f+1;break;case "+Skill":e.selectedIndex=4;Object.entries(info.types.qurious).forEach(([g,m],n)=>{g.includes(k)&&(f=n);n=document.createElement("option");
n.value=-m;n.title=`${g} +1 -${m}Pts`;n.textContent=`${g} ${m}Pts`;h.appendChild(n)});h.selectedIndex=f+1;break;case "+Slots":e.selectedIndex=3;for(d=1;3>=d;d++){e=-6*d;const g=document.createElement("option");g.value=e;g.textContent=`+${d} Slot${1===d?"s":""} ${e}`;h.appendChild(g)}h.selectedIndex=k/-6}++c})},setUsedDecorations=a=>{document.querySelectorAll(".decoDisplay>img.armorDeco").forEach(b=>{a[b.className[22]-1]&&Object.values(b.nextElementSibling.children).some((c,d)=>{if(+c.value<=b.className[22]&&
c.textContent.includes(a[b.className[22]-1][0]))return b.nextElementSibling.selectedIndex=d,a[b.className[22]-1].shift()})})},setAugmentDropdown=(a,b)=>{for(let c=0;c<a.childElementCount;c++)if(a.children[c].textContent.includes(b)){a.selectedIndex=c;setArmorSkillsDisplay([a.id]);break}},setCharmSelects=a=>{a=Object.keys(a);const b=document.querySelectorAll("select.charm");for(let c=0;c<a.length;c++){const d=b[c];for(let e=0;e<d.options.length;e++)if(d.options[e].textContent.includes(a[c])){d.selectedIndex=
e;setCharmsAvailableDecoSlots(d);break}}},equipBuild=(a,b)=>{const {armors:c,usedSkills:d}=a;setCharmSelects(b);for(const [e,h]of c)setAugmentDropdown(document.getElementById(h.type),e),resetAugmentSelections(h.type),setArmorSkillsDisplay([h.type]);for(const e of c)a=document.querySelectorAll(`#${e[1].type}Qurious>select.augmentType`),setAugmentAuto(e[1],a),validator(document.getElementById(`${e[1].type}Qurious`));document.getElementById("damage").classList.remove("augInvis");setUsedDecorations(getUsedDecoArr(d));
updateSelectedSkillsDisplay()},appendElements=()=>{requestIdleCallback(()=>document.querySelector(".grid")?.append(GlobalFragment))},setUsedDecos=a=>{["lvl4","lvl3","lvl2","lvl1"].forEach(b=>{const c=a.usedSkills.filter(e=>e[2].includes(b)),d=document.querySelectorAll(`.${b}:not(".augInvis")`);for(let e=0;e<c.length;e++)for(let h=0;h<Object.values(d[e].children).length;)if(d[e].children[h].value<=b&&d[e].children[h].textContent.includes(c[e][0])){d[e].selectedIndex=h;break}})},getTotal=(a=info.types)=>
{const b=getSetRequirements().skills,{armorSkills:c,remainingSlots:d,quriousSkills:e}=newSkills;for(let l=0;4>l;++l)if(d[l])for(let [k,f]of Object.entries(a.decoLevels[l]))c[k]=c[k]?c[k]+ +f*d[l]:+f*d[l];Object.entries(a.qurious).forEach(([l,k])=>{e[~~(k/3)-1]&&(c[l]=c[l]?c[l]+e[k/3-1]:e[k/3-1])});let h=[];Object.entries(c).forEach(([l,k])=>{isNaN(l)&&(b[l]&&(a.maxLevel[l]&&0<a.maxLevel[l]+b[l]||info.skills[l]&&0<info.skills[l].length-1+b[l])?h.push([l,Math.min(+k,a.maxLevel[l]?a.maxLevel[l]+b[l]:
info.skills[l].length-1+b[l])]):b[l]||h.push([l,Math.min(+k,a.maxLevel[l]??info.skills[l].length-1)]))});return h.sort()},setOutput=a=>{let b="";a.forEach(c=>{0!=c[1]&&(b+=`<button>${c[0]} +${+c[1]}</button>`)});document.querySelector(".extraSkills").innerHTML=b;document.getElementById("extraOutput").textContent=`Found ${formatNumbers(totalSets)} Builds / ${formatNumbers(totalCombos)} Combinations`;console.log((performance.now()-timer)/1E3)},getUsedCharm=a=>a.map(b=>{b=b.usedSkills.slice(-2);return`${b[0][0]}: ${b[0][1]} & ${b[1][0]}: ${b[1][1]}`}),
receiveMessage=(a,b)=>{for(let k=0;k<a.length;k++){var c=a[k];if(100>GlobalMap.size){GlobalMap.set(GlobalMap.size,c);var d=getUsedCharm(c),e=document.createDocumentFragment(),h=document.createElement("button");h.type="button";h.setAttribute("aria-pressed","false");h.classList.add("equipBuild");h.textContent="Equip Build";e.appendChild(h);for(h=0;5>h;h++){var l=document.createElement("output");l.className=`armorImg ${["helm","chest","arm","waist","leg"][h]}`;e.appendChild(l);l=document.createElement("span");
l.textContent=c[0].armors[h][0];e.appendChild(l)}const f=document.createElement("select");f.classList.add("armorCharm");f.setAttribute("title","charmSkill1");c=document.createElement("output");c.className="armorImg charm";e.appendChild(c);d.forEach(g=>{const m=document.createElement("option");m.value=g;m.textContent=g;f.appendChild(m)});e.appendChild(f);d=document.createElement("div");d.classList.add("setResult");d.appendChild(e);GlobalFragment.append(d)}if(100===GlobalMap.size||k===a.length&&b&&
100>GlobalMap.size){e=0;for(d=0;100>=d&&GlobalMap.has(d);d++)e+=GlobalMap.get(d).length;document.querySelector(".grid").append(GlobalFragment);document.getElementById("setOutput").textContent=`Displayed ${Math.min(100,GlobalMap.size)} Builds / ${formatNumbers(e)} Combinations`;GlobalMap.set("finished",!0)}}},getSkillReq=(a=[])=>{document.querySelectorAll(".buildSkills>div>.skill").forEach(b=>{0<b.selectedIndex&&a.push([b.id,b.selectedIndex])});return a},getSetRequirements=(a=info.types)=>{const b=
{},c={};document.querySelectorAll("#skillSelect>div>output").forEach(d=>{0<+d.textContent.match(/(?<=Lv-)\d/)[0]&&(b[d.className.split(" ")[1]]=-d.textContent.match(/(?<=Lv-)\d/)[0],c[d.className.split(" ")[1]]={lvl:a.decos[d.className.split(" ")[1]]??5,lvl4:a.Lvl4[d.className.split(" ")[1]]??0,max:a.maxLevel[d.className.split(" ")[1]]-+d.textContent.match(/(?<=Lv-)\d/)[0],qurious:~~((a.qurious[d.className.split(" ")[1]]??60)/3)})});return{skills:Object.fromEntries(Object.entries(b).sort((d,e)=>c[e[0]].qurious-
c[d[0]].qurious||c[e[0]].lvl-c[d[0]].lvl||c[d[0]].lvl4*c[d[0]].qurious-c[e[0]].lvl4*c[e[0]].qurious)),skillInfo:c}};
function applyArmorFilter(a,b,c){let d=new Map(Object.entries(JSON.parse(JSON.stringify(info.armor))));const e={},h=[1,8.5,8.5,9];for(let l=0;5>l;l++){const k=["helm","waist","chest","arm","leg"][l];d.set(k,d.get(k).filter(f=>"MaleOnly"!==f.sex))}["helm","waist","chest","arm","leg"].forEach(l=>{e[l]=[];d.get(l).forEach(k=>{if(k){var f={},g=k.skills;if(13!==k.quriousTable){var m=Object.entries(k.decoAugments).filter(p=>3>=p[0]&&2==p[1][0]).pop();if(m){let [p,[,q]]=m;f.decos=q;f.augs=[{"+Slots":-6*
p}];f.quriousPoints=k.quriousPoints-6*p;f.decoAugments=k.decoAugments}}else 13===k.quriousTable&&(f.decos=[1,1,0,1],f.quriousPoints=0,f.augs=[{def:5},{def:5},{def:5},{def:5},{"+Slots":-18},{"+Slots":-12}]);f.augs||(f.decos=k.decos,f.augs=[],f.quriousPoints=k.quriousPoints,f.decoAugments=k.decoAugments);if(3<document.getElementById("StormSoul").selectedIndex){m=4===document.getElementById("StormSoul").selectedIndex?1:2;for(var n of g)6>b[n].qurious&&(g[n]+=m)}f.fodderSkills=[];f.fodderCount=0;n=f.decos[0]*
h[0]+f.decos[1]*h[1]+f.decos[2]*h[2]+f.decos[3]*h[3];for(const [p,q]of Object.entries(g))if(a[p])a[p]?(5<b[p].qurious&&4<b[p].lvl&&(f.setBonus={[p]:q},n+=30*Math.min(-1*a[p],g[p])),n+=Math.min(-1*a[p],g[p])*(20===b[p].qurious?4:b[p].qurious/3)):13!=k.quriousTable||f.fodderCount||(f.fodderCount=0);else for(f.fodderCount+=q,m=0;m<q;m++)f.fodderSkills.push(p);if(13===k.quriousTable)f.unBloatedPoints=0,f.armorRating=n;else switch(f.fodderCount){case 0:f.quriousPoints+=15;f.unBloatedPoints=~~(f.quriousPoints/
3);f.augs=f.augs[0]?[{"-Def":5},{"-Def":5},{"-Def":5}].concat(f.augs):[{"-Def":5},{"-Def":5},{"-Def":5}];f.armorRating=n+f.unBloatedPoints;break;case 1:f.quriousPoints+=20;f.unBloatedPoints=~~(f.quriousPoints/3);f.augs=f.augs?[{"-Skill":f.fodderSkills.pop()},{"-Def":5},{"-Def":5}].concat(f.augs):[{"-Skill":f.fodderSkills.pop()},{"-Def":5},{"-Def":5}];f.armorRating=n+f.unBloatedPoints;break;case 2:f.quriousPoints+=25;f.unBloatedPoints=~~(f.quriousPoints/3);f.augs=f.augs?[{"-Skill":f.fodderSkills.pop()},
{"-Skill":f.fodderSkills.pop()},{"-Def":5}].concat(f.augs):[{"-Skill":f.fodderSkills.pop()},{"-Skill":f.fodderSkills.pop()},{"-Def":5}];f.armorRating=n+f.unBloatedPoints;break;default:f.quriousPoints+=30,f.unBloatedPoints=~~(f.quriousPoints/3),f.augs=f.augs?[{"-Skill":f.fodderSkills.pop()},{"-Skill":f.fodderSkills.pop()},{"-Skill":f.fodderSkills.pop()}].concat(f.augs):[{"-Skill":f.fodderSkills.pop()},{"-Skill":f.fodderSkills.pop()},{"-Skill":f.fodderSkills.pop()}],f.armorRating=n+f.unBloatedPoints}g=
(p,q=!0)=>{q&&e[l].pop();f.name=k.name;f.type=l;f.skills=k.skills;e[l].splice(p,0,f)};if(!e[l][0])f.name=k.name,f.type=l,f.skills=k.skills,e[l].push(f);else if(f.armorRating>(e[l].length===c?e[l][c-1].armorRating:10)){for(n=0;n<e[l].length;n++)if(f.armorRating>e[l][n].armorRating){g(n);return}e[l].length<c&&g(e[l].length-1,!1)}}})});return e}
const getCharms=(a,b,c=[])=>{const {charms:d,types:e}=info;Object.values(d).filter(h=>Object.entries(h.skills).every(([l,k])=>0>=a[l]+k&&3>e.Lvl4[l])).forEach(h=>{c.push({...h.skills})});return c},getCheckedSkills=(a=[])=>{document.getElementsByClassName("skillButton").forEach(b=>{b.checked&&a.push(info.skills[b.id])});return a},getSetBuilds=(a=15)=>{try{timer=performance.now();workerCount=3;let b=Object.values(document.getElementsByTagName("SCRIPT")).some(k=>k.src.includes("backup.js"))?"./setBuilderWorker.js":
"./ugly/onlineWorker.js";for(let k=0;k<workerCount;k++)workers[k]=new Worker(b);workers.forEach(k=>k.addEventListener("message",f=>{totalCombos+=f.data[2][1];totalSets+=f.data[2][0];(100>GlobalMap.size&&f.data[0][0]||f.data[1])&&receiveMessage(f.data[0],f.data[1]);if(f.data[1]){f.target.terminate();--workerCount;f=f.data[1];for(var g=0;4>g;g++){var m=newSkills.remainingSlots[g],n=f.remainingSlots[g];newSkills.remainingSlots[g]=m>=n?m:n}for(g=0;5>g;g++)m=newSkills.quriousSkills[g],n=f.quriousSkills[g],
newSkills.quriousSkills[g]=m>=n?m:n;for(const [p,q]of Object.entries(f.armorSkills))f=newSkills.armorSkills[p],newSkills.armorSkills[p]=f>=q?f:q;if(0===workerCount)if(setOutput(getTotal()),0<GlobalFragment.childElementCount){f=0;for(m=0;100>=m&&GlobalMap.has(m);m++)f+=GlobalMap.get(m).length;document.querySelector(".grid").append(GlobalFragment);document.getElementById("setOutput").textContent=`Displayed ${Math.min(100,GlobalMap.size)} Builds / ${formatNumbers(f)} Combinations`;GlobalMap.set("finished",
!0)}else 0===GlobalMap.size&&(document.getElementById("setOutput").textContent="Displayed 0 Builds / 0 Combinations")}}));const c=getSetRequirements();c.charmSlots=document.getElementById("extraCharmDeco").checked?[1,0,1,0]:[2,0,1,0];c.thisWeapon=getWeaponMR().decos;c.theseCharms=getCharms(c.skills,c.skillInfo);c.armors=applyArmorFilter(c.skills,c.skillInfo,a);const d={};for(const [k,f]of Object.entries(c.armors))for(const [g,m]of Object.entries(f)){if(!m.setBonus||!c.skills[Object.keys(m.setBonus)[0]])continue;
let n=Object.keys(m.setBonus)[0];d[n]||(d[n]=[]);d[n].push(k,+g,-1*m.setBonus[n])}const e={helm:-1,chest:0,arm:0,waist:0,leg:0,workers:0},h=[];(k=>{const f=Object.keys(d).length;a:for(;;){if(!(++e.helm<k||(e.helm=0,++e.chest<k||(e.chest=0,++e.arm<k||(e.arm=0,++e.waist<k||(e.waist=0,++e.leg!==k))))))break a;if(f)for(const g in d){let m=0,n=d[g],p=n.length-1;for(;!(n[p-1]===e[n[p-2]]&&(m+=n[p]),0>(p-=3)););if(c.skills[g]<m)continue a}h.push([e.helm,e.chest,e.arm,e.waist,e.leg])}})(a);for(const k in d)delete c.skills[k];
GlobalMap.clear();const l=h.length;for(a=0;a<workers.length;++a)c.permutations=a===workers.length-1?h:h.splice(0,l/workers.length),workers[a].postMessage(c);document.getElementById("setReturn").classList.remove("augInvis");document.getElementById("damage").classList.add("augInvis");document.querySelector(".extraSkills").innerHTML="<P2 style='font-size:18px !important; height:15em !important;'>Searching...</P2>";document.getElementsByClassName("grid")[0].innerHTML="";newSkills={remainingSlots:[0,0,
0,0],armorSkills:{},quriousSkills:[0,0,0,0,0]};totalSets=totalCombos=0}catch(b){console.error(b)}},build=a=>{"Dereliction CriticalEye CriticalBoost MaximumMight RecoilDown ReloadSpeed RapidFireUp PierceUp Burst Agitator AttackBoost".split(" ").forEach(b=>createSkillSelections(b,info.types.maxLevel[b]));getSetBuilds(15);return GlobalMap};
